const fs = require('fs');
const L = [];
const a = (l) => L.push(l);

a('/**');
a(' * E2E tests: Hot-loading params and pin loading mode via UI interactions.');
a(' *');
a(' * Tests:');
a(' *   1. Hot-loading model params -- change BF/IS on BJT via primary param inputs in');
a(' *      the Model section of the property popup, verify collector voltage changes.');
a(' *   2. Hot-loading pin electrical params -- change rOut on And gate output pin,');
a(' *      verify override persists and simulation output changes.');
a(' *   3. Pin loading mode switch via context menu on digital-to-analog wire --');
a(' *      switch to Loaded, verify checkmark appears and simulation continues.');
a(' *   4. Pin loading mode Ideal -- verify valid finite output after mode change.');
a(' */');
a('');
a("import { test, expect, type Page } from '@playwright/test';");
a("import { UICircuitBuilder } from '../fixtures/ui-circuit-builder';");
a('');
a('// ---------------------------------------------------------------------------');
a('// Shared helper: open property popup for a labeled element by double-click');
a('// ---------------------------------------------------------------------------');
a('');
a('async function openPopupForLabel(builder: UICircuitBuilder, label: string): Promise<void> {');
a('  const info = await builder.getCircuitInfo();');
a('  const el = info.elements.find(e => e.label === label);');
a('  expect(el, `Element "${label}" not found`).toBeTruthy();');
a('  const coords = await builder.toPageCoords(el!.center.screenX, el!.center.screenY);');
a('  await builder.page.mouse.dblclick(coords.x, coords.y);');
a("  await expect(builder.page.locator('.prop-popup')).toBeVisible({ timeout: 3000 });");
a('}');
a('');
a('/**');
a(' * Set a model parameter value in the property popup by finding the row whose');
a(' * label span exactly matches paramKey and filling the adjacent input.');
a(' * Works for both primary params (visible immediately) and secondary params');
a(' * (inside the Advanced Parameters section -- expand first if needed).');
a(' */');
a('async function setModelParamInPopup(');
a('  page: Page,');
a('  paramKey: string,');
a('  value: string | number,');
a('): Promise<void> {');
a("  const popup = page.locator('.prop-popup');");
a('  const inputHandle = await popup.evaluateHandle((popupEl, key) => {');
a('    const spans = popupEl.querySelectorAll("label, span");');
a('    for (const span of spans) {');
a('      if (span.textContent?.trim() === key) {');
a('        const row = span.parentElement;');
a('        if (row) {');
a('          const input = row.querySelector("input");');
a('          if (input) return input;');
a('        }');
a('      }');
a('    }');
a('    return null;');
a('  }, paramKey);');
a('  const input = inputHandle.asElement();');
a('  expect(input, `Model param "${paramKey}" input not found`).not.toBeNull();');
a('  await input!.fill(String(value));');
a("  await input!.press('Tab');");
a('}');
a('');
a('/**');
a(' * Expand the Pin Electrical collapsible section in the property popup.');
a(' */');
a('async function expandPinElectricalSection(page: Page): Promise<void> {');
a("  const popup = page.locator('.prop-popup');");
a("  const toggle = popup.getByText('\u25b6 Pin Electrical');");
a('  await expect(toggle).toBeVisible({ timeout: 3000 });');
a('  await toggle.click();');
a("  await expect(popup.getByText('\u25bc Pin Electrical')).toBeVisible({ timeout: 1000 });");
a('}');
a('');
a('/**');
a(' * Find the input for a pin electrical field by its display label (e.g. Rout).');
a(' */');
a('async function getPinFieldInput(page: Page, fieldLabel: string) {');
a("  const popup = page.locator('.prop-popup');");
a('  const rows = popup.locator("div").filter({');
a('    has: page.locator(`span:text-is("${fieldLabel}")`),');
a('  });');
a('  return rows.locator("input").first();');
a('}');
a('');
a('// ---------------------------------------------------------------------------');
a('// Shared circuit builder: mixed digital-to-analog (And gate -> Resistor -> GND)');
a('// ---------------------------------------------------------------------------');
a('');
a('/**');
a(' * Build a mixed digital-to-analog circuit using already-loaded builder.');
a(' * And gate A1 (both inputs HIGH) -> RL (1kOhm) -> GND, Probe P1 on junction.');
a(' * Returns page-absolute midpoint of the wire between A1.out and RL.A.');
a(' */');
a('async function buildMixedCircuitAndGetWireMid(');
a('  builder: UICircuitBuilder,');
a('): Promise<{ wireMidX: number; wireMidY: number }> {');
a("  await builder.placeLabeled('And', 4, 8, 'A1');");
a("  await builder.placeLabeled('Resistor', 12, 8, 'RL');");
a("  await builder.placeComponent('Ground', 14, 14);");
a("  await builder.placeLabeled('Probe', 18, 8, 'P1');");
a("  await builder.placeLabeled('In', 1, 6, 'Inp1');");
a("  await builder.placeLabeled('In', 1, 10, 'Inp2');");
a("  await builder.setComponentProperty('Inp1', 'Default', 1);");
a("  await builder.setComponentProperty('Inp2', 'Default', 1);");
a("  await builder.setComponentProperty('RL', 'resistance', 1000);");
a('');
a("  await builder.drawWire('Inp1', 'out', 'A1', 'In_1');");
a("  await builder.drawWire('Inp2', 'out', 'A1', 'In_2');");
a("  await builder.drawWire('A1', 'out', 'RL', 'A');")
a("  await builder.drawWire('RL', 'A', 'P1', 'in');");
a("  await builder.drawWireFromPin('RL', 'B', 14, 14);");
a('');
a("  const fromPos = await builder.getPinPagePosition('A1', 'out');");
a("  const toPos = await builder.getPinPagePosition('RL', 'A');");
a('  const wireMidX = Math.round((fromPos.x + toPos.x) / 2);');
a('  const wireMidY = Math.round((fromPos.y + toPos.y) / 2);');
a('');
a('  return { wireMidX, wireMidY };');
a('}');
a('');
a('// ---------------------------------------------------------------------------');
a('// Test suite 1: Hot-loading SPICE model params via property popup');
a('// ---------------------------------------------------------------------------');
a('');
a("test.describe('Hot-loading model params via property popup', () => {");
a("  test('changing BF on BJT via primary param row changes output voltage', async ({ page }) => {");
a('    const builder = new UICircuitBuilder(page);');
a('    await builder.load();');
a('');
a('    // BJT common-emitter: Vcc(12V)->Rc(10k)->Q1:C, Ib(1mA)->Q1:B,');
a('    // Q1:E->GND, Probe Pc on collector');
a('    // With BF=100 (default): Ic = BF*Ib = 100*1mA = 100mA but Rc limits it');
a('    // With BF=10: Ic = 10*1mA = 10mA, Vc = 12 - 10mA*10k = 2V');
a('    // With BF=100: Ic = 100*1mA = 100mA (saturated), Vc near 0V');
a('    // So changing BF changes the output voltage significantly');
a("    await builder.placeLabeled('DcVoltageSource', 3, 5, 'Vcc');");
a("    await builder.placeLabeled('CurrentSource', 3, 12, 'Ib');");
a("    await builder.placeLabeled('Resistor', 10, 5, 'Rc');");
a("    await builder.placeLabeled('NpnBJT', 16, 9, 'Q1');");
a("    await builder.placeComponent('Ground', 6, 16);");
a("    await builder.placeComponent('Ground', 18, 16);");
a("    await builder.placeComponent('Ground', 6, 9);");
a("    await builder.placeLabeled('Probe', 22, 7, 'Pc');");
a('');
a("    await builder.setComponentProperty('Vcc', 'voltage', 12);");
a("    await builder.setComponentProperty('Ib', 'Current (A)', 0.001);");
a("    await builder.setComponentProperty('Rc', 'resistance', 10000);");
a('');
a("    await builder.drawWire('Vcc', 'pos', 'Rc', 'A');");
a("    await builder.drawWire('Rc', 'B', 'Q1', 'C');");
a("    await builder.drawWire('Ib', 'pos', 'Q1', 'B');");
a("    await builder.drawWireFromPin('Q1', 'E', 18, 16);");
a("    await builder.drawWireFromPin('Vcc', 'neg', 6, 16);");
a("    await builder.drawWireFromPin('Ib', 'neg', 6, 9);");
a("    await builder.drawWire('Rc', 'B', 'Pc', 'in');");
a('');
a('    // Baseline step with DEFAULT BF=100');
a('    await builder.stepViaUI();');
a('    await builder.verifyNoErrors();');
a('    const defaultState = await builder.stepAndReadAnalog(200);');
a('    expect(defaultState).not.toBeNull();');
a("    const vcDefault = defaultState!.nodeVoltages['Pc'];");
a('    expect(vcDefault).toBeDefined();');
a('');
a('    // Open popup and change BF from 100 to 10 via the primary param row');
a("    await openPopupForLabel(builder, 'Q1');");
a("    await setModelParamInPopup(page, 'BF', 10);");
a('    await page.keyboard.press("Escape");');
a('');
a('    // Step again to pick up hot-loaded BF change');
a('    const hotState = await builder.stepAndReadAnalog(200);');
a('    expect(hotState).not.toBeNull();');
a("    const vcHot = hotState!.nodeVoltages['Pc'];");
a('    expect(vcHot).toBeDefined();');
a('');
a('    // Collector voltage must differ between BF=100 and BF=10');
a('    // At least 0.5V difference expected (likely much more)');
a('    expect(Math.abs(vcHot! - vcDefault!)).toBeGreaterThan(0.5);');
a('  });');
a('});');
a('');
a('// ---------------------------------------------------------------------------');
a('// Test suite 2: Hot-loading pin electrical params via property popup');
a('// ---------------------------------------------------------------------------');
a('');
a("test.describe('Hot-loading pin electrical params via property popup', () => {");
a("  test('rOut override on And gate output pin persists after close and reopen', async ({ page }) => {");
a('    const builder = new UICircuitBuilder(page);');
a('    await builder.load();');
a('');
a("    await builder.placeLabeled('And', 10, 10, 'G1');");
a('');
a("    await openPopupForLabel(builder, 'G1');");
a('    await expandPinElectricalSection(page);');
a('');
a("    const rOutInput = await getPinFieldInput(page, 'Rout');");
a('    await expect(rOutInput).toBeVisible({ timeout: 2000 });');
a("    await rOutInput.fill('75');");
a("    await rOutInput.press('Tab');");
a('    await page.waitForTimeout(100);');
a('    await page.keyboard.press("Escape");');
a('');
a('    // Reopen popup and verify rOut value persisted');
a("    await openPopupForLabel(builder, 'G1');");
a('    await expandPinElectricalSection(page);');
a('');
a("    const rOutAfter = await getPinFieldInput(page, 'Rout');");
a('    await expect(rOutAfter).toBeVisible({ timeout: 2000 });');
a('    const displayedValue = await rOutAfter.inputValue();');
a('    // Override was stored -- input must be non-empty');
a("    expect(displayedValue.trim()).not.toBe('');");
a('    await page.keyboard.press("Escape");');
a('  });');
a('');
a("  test('rOut override affects simulation output in mixed-signal mode', async ({ page }) => {");
a('    const builder = new UICircuitBuilder(page);');
a('    await builder.load();');
a('');
a('    // Mixed circuit: And gate A1 (inputs HIGH) -> RL (1kOhm) -> GND, Probe P1 at junction');
a('    // rOut is source impedance: V_junction = Voh * RL / (rOut + RL)');
a('    // Large rOut => small V_junction');
a("    await builder.placeLabeled('And', 4, 8, 'A1');");
a("    await builder.placeLabeled('Resistor', 12, 8, 'RL');");
a("    await builder.placeComponent('Ground', 14, 14);");
a("    await builder.placeLabeled('Probe', 18, 8, 'P1');");
a("    await builder.placeLabeled('In', 1, 6, 'Inp1');");
a("    await builder.placeLabeled('In', 1, 10, 'Inp2');");
a("    await builder.setComponentProperty('Inp1', 'Default', 1);");
a("    await builder.setComponentProperty('Inp2', 'Default', 1);");
a("    await builder.setComponentProperty('RL', 'resistance', 1000);");
a('');
a("    await builder.drawWire('Inp1', 'out', 'A1', 'In_1');");
a("    await builder.drawWire('Inp2', 'out', 'A1', 'In_2');");
a("    await builder.drawWire('A1', 'out', 'RL', 'A');");
a("    await builder.drawWire('RL', 'A', 'P1', 'in');");
a("    await builder.drawWireFromPin('RL', 'B', 14, 14);");
a('');
a('    // Baseline measurement with default rOut');
a('    await builder.stepViaUI();');
a('    await builder.verifyNoErrors();');
a('    const defaultState = await builder.stepAndReadAnalog(50);');
a('    expect(defaultState).not.toBeNull();');
a("    const vDefault = defaultState!.nodeVoltages['P1'];");
a('    expect(vDefault).toBeDefined();');
a('    expect(vDefault).toBeGreaterThan(0);');
a('');
a('    // Override rOut to 100000 Ohm via Pin Electrical popup');
a("    await openPopupForLabel(builder, 'A1');");
a('    await expandPinElectricalSection(page);');
a("    const rOutInput = await getPinFieldInput(page, 'Rout');");
a('    await expect(rOutInput).toBeVisible({ timeout: 2000 });');
a("    await rOutInput.fill('100000');");
a("    await rOutInput.press('Tab');");
a('    await page.waitForTimeout(100);');
a('    await page.keyboard.press("Escape");');
a('');
a('    // Step with hot-loaded rOut override');
a('    await builder.stepViaUI();');
a('    await builder.verifyNoErrors();');
a('    const overrideState = await builder.stepAndReadAnalog(50);');
a('    expect(overrideState).not.toBeNull();');
a("    const vOverride = overrideState!.nodeVoltages['P1'];");
a('    expect(vOverride).toBeDefined();');
a('');
a('    // rOut=100kOhm >> RL=1kOhm: V_junction = Voh*1k/101k ~= 0.05V');
a('    // vs default rOut giving V_junction near Voh (>4V)');
a('    expect(vOverride).toBeLessThan(vDefault! - 0.5);');
a('    expect(isNaN(vOverride!)).toBe(false);');
a('  });');
a('});');
a('');
a('// ---------------------------------------------------------------------------');
a('// Test suite 3: Pin loading mode switch via context menu');
a('// ---------------------------------------------------------------------------');
a('');
a("test.describe('Pin loading mode switch via UI context menu', () => {");
a("  test('context menu on digital-to-analog wire shows all three Pin Loading options', async ({ page }) => {");
a('    const builder = new UICircuitBuilder(page);');
a('    await builder.load();');
a('');
a('    const { wireMidX, wireMidY } = await buildMixedCircuitAndGetWireMid(builder);');
a('');
a("    await page.mouse.click(wireMidX, wireMidY, { button: 'right' });");
a('    await page.waitForTimeout(200);');
a('');
a("    const menu = page.locator('.ctx-menu');");
a('    await expect(menu).toBeVisible({ timeout: 3000 });');
a('');
a('    const labels = await page.evaluate(() => {');
a("      const items = document.querySelectorAll('.ctx-menu-item .ctx-menu-label');");
a('      return Array.from(items).map(el => el.textContent ?? "");');
a('    });');
a('');
a("    expect(labels.some(l => l.includes('Pin Loading: Loaded'))).toBe(true);");
a("    expect(labels.some(l => l.includes('Pin Loading: Ideal'))).toBe(true);");
a("    expect(labels.some(l => l.includes('Pin Loading: Default'))).toBe(true);");
a('  });');
a('');
a("  test('selecting Pin Loading: Loaded shows checkmark and simulation continues without error', async ({ page }) => {");
a('    const builder = new UICircuitBuilder(page);');
a('    await builder.load();');
a('');
a('    const { wireMidX, wireMidY } = await buildMixedCircuitAndGetWireMid(builder);');
a('');
a('    // Baseline step confirms simulation runs');
a('    await builder.stepViaUI();');
a('    await builder.verifyNoErrors();');
a('');
a('    // Switch to Loaded');
a("    await page.mouse.click(wireMidX, wireMidY, { button: 'right' });");
a('    await page.waitForTimeout(200);');
a('');
a("    const loadedItem = page.locator('.ctx-menu-item .ctx-menu-label').filter({");
a("      hasText: 'Pin Loading: Loaded',");
a('    });');
a('    await expect(loadedItem).toBeVisible({ timeout: 3000 });');
a('    await loadedItem.click();');
a('    await page.waitForTimeout(300);');
a('');
a('    // Canvas must still be visible (no crash)');
a("    await expect(page.locator('#sim-canvas')).toBeVisible();");
a('');
a('    // Step again after mode switch -- must not crash');
a('    await builder.stepViaUI();');
a('    await builder.verifyNoErrors();');
a('');
a('    // Checkmark must appear on the Loaded option');
a("    await page.mouse.click(wireMidX, wireMidY, { button: 'right' });");
a('    await page.waitForTimeout(200);');
a('');
a('    const updatedLabels = await page.evaluate(() => {');
a("      const items = document.querySelectorAll('.ctx-menu-item .ctx-menu-label');");
a('      return Array.from(items).map(el => el.textContent ?? "");');
a('    });');
a('');
a("    const loadedLabel = updatedLabels.find(l => l.includes('Pin Loading: Loaded'));");
a('    expect(loadedLabel).toBeDefined();');
a('    expect(loadedLabel).toContain("\u2713");');
a('  });');
a('');
a("  test('switching to Pin Loading: Ideal produces valid finite simulation output', async ({ page }) => {");
a('    const builder = new UICircuitBuilder(page);');
a('    await builder.load();');
a('');
a('    const { wireMidX, wireMidY } = await buildMixedCircuitAndGetWireMid(builder);');
a('');
a('    // Baseline with Default loading');
a('    await builder.stepViaUI();');
a('    await builder.verifyNoErrors();');
a('    const defaultState = await builder.stepAndReadAnalog(100);');
a('    expect(defaultState).not.toBeNull();');
a("    const vDefault = defaultState!.nodeVoltages['P1'];");
a('    expect(vDefault).toBeDefined();');
a('    expect(vDefault).toBeGreaterThan(0);');
a('');
a('    // Switch to Ideal (zero output impedance)');
a("    await page.mouse.click(wireMidX, wireMidY, { button: 'right' });");
a('    await page.waitForTimeout(200);');
a('');
a("    const idealItem = page.locator('.ctx-menu-item .ctx-menu-label').filter({");
a("      hasText: 'Pin Loading: Ideal',");
a('    });');
a('    await expect(idealItem).toBeVisible({ timeout: 3000 });');
a('    await idealItem.click();');
a('    await page.waitForTimeout(300);');
a('');
a('    await builder.stepViaUI();');
a('    await builder.verifyNoErrors();');
a('    const idealState = await builder.stepAndReadAnalog(100);');
a('    expect(idealState).not.toBeNull();');
a("    const vIdeal = idealState!.nodeVoltages['P1'];");
a('    expect(vIdeal).toBeDefined();');
a('');
a('    // Ideal mode (rOut=0): full Voh at junction; Default (rOut>0): reduced');
a('    // Both must be positive and finite; Ideal >= Default');
a('    expect(isNaN(vIdeal!)).toBe(false);');
a('    expect(isFinite(vIdeal!)).toBe(true);');
a('    expect(vIdeal).toBeGreaterThan(0);');
a('    expect(vIdeal).toBeGreaterThanOrEqual(vDefault! - 0.01);');
a('  });');
a('});');

const content = L.join('\n') + '\n';
fs.writeFileSync('C:/local_working_projects/digital_in_browser/e2e/gui/hotload-params-e2e.spec.ts', content, 'utf-8');
console.log('written', L.length, 'lines,', content.length, 'chars');
