var fs=require("fs");
var B=String.fromCharCode(96);
var L=[];
L.push("# Review Report: Phase 6 — Engine integration (checkpoint/rollback/acceptTimestep + Readonly narrowing)");
L.push("");
L.push("## Summary");
L.push("");
L.push("| Item | Value |");
L.push("|------|-------|");
L.push("| Tasks reviewed | 4 (G1, W6T1, W6T2, W6T3) |");
L.push("| Violations | 7 (0 critical, 3 major, 4 minor) |");
L.push("| Gaps | 3 |");
L.push("| Weak tests | 3 |");
L.push("| Legacy references | 4 |");
L.push("| Verdict | **has-violations** |");
L.push("");
L.push("---");
L.push("");
L.push("## Violations");
L.push("");
L.push("### V1 — MAJOR: Historical-provenance comment in analog-engine.ts field declaration block");
L.push("");
L.push("**File:** " + B + "src/solver/analog/analog-engine.ts" + B + "  ");
L.push("**Lines:** 87-92");
L.push("");
L.push("**Rule violated:** Rules — No historical-provenance comments. Any comment describing what code replaced, what it used to do, why it changed, or where it came from is banned.");
L.push("");
L.push("**Evidence (lines 87-92):**");
L.push(B+B+B);
L.push("// " + B + "_stateCheckpoint" + B + " replaces the old " + B + "StatePool.checkpoint()" + B + " allocation:");
L.push("// instead of allocating a fresh Float64Array every step to snapshot");
L.push("// " + B + "statePool.state0" + B + " (which was done unconditionally even when no rollback");
L.push("// occurred), we keep a persistent scratch buffer owned by the engine and");
L.push("// copy into it via " + B + ".set()" + B + ".");
L.push(B+B+B);
L.push("");
L.push("The comment names the removed API (" + B + "StatePool.checkpoint()" + B + "), describes what it used to do (allocating a fresh Float64Array every step), and explains what replaced it. This is a textbook historical-provenance comment: it describes what changed, what was removed, and why.");
L.push("");
L.push("**Severity:** Major");
L.push("");
L.push("---");
L.push("");
L.push("### V2 — MAJOR: Historical-provenance comment — \"legacy r variable\"");
L.push("");
L.push("**File:** " + B + "src/solver/analog/analog-engine.ts" + B + "  ");
L.push("**Line:** 352");
L.push("");
L.push("**Rule violated:** Rules — No historical-provenance comments.");
L.push("");
L.push("**Evidence (line 352):**");
L.push(B+B+B);
L.push("// convert to the legacy " + B + "r" + B + " variable (r >= 1 = accept) so the existing");
L.push("// " + B + "shouldReject" + B + " / " + B + "computeNewDt" + B + " plumbing works unchanged.");
L.push(B+B+B);
L.push("");
L.push("The comment explicitly names this as a 'legacy' variable and explains that the old name is preserved to avoid changing other code ('so the existing plumbing works unchanged'), documenting an in-flight migration where both naming conventions coexist. A justification comment that names the legacy API makes the violation worse, not better.");
L.push("");
L.push("**Severity:** Major");
L.push("");
L.push("---");
L.push("");
L.push("### V3 — MAJOR: compiled-analog-circuit.ts backwards-compatibility fallback not remediated (V5 from Wave 6.1)");
L.push("");
L.push("**File:** " + B + "src/solver/analog/compiled-analog-circuit.ts" + B + "  ");
L.push("**Lines:** 133, 150");
L.push("");
L.push("**Rule violated:** Rules — No fallbacks. No backwards compatibility shims. No safety wrappers.");
L.push("");
L.push("**Evidence:**");
L.push(B+B+B+"typescript");
L.push("statePool?: StatePool;                                    // line 133 - optional param");
L.push("// ...");
L.push("this.statePool = params.statePool ?? new StatePool(0);   // line 150 - silent fallback");
L.push(B+B+B);
L.push("");
L.push("This was flagged as V5 (minor) in the Wave 6.1 review. " + B + "progress.md" + B + " records that " + B + "G1 (review gap)" + B + " and " + B + "V2+G3" + B + " were fixed but V5 is not listed as remediated. The fallback " + B + "new StatePool(0)" + B + " silently produces a zero-slot pool instead of failing when a pool is absent. The spec requires every compiled circuit to carry a properly allocated pool.");
L.push("");
L.push("**Severity:** Major");
L.push("");
L.push("---");
L.push("");
L.push("### V4 — MINOR: analog-engine.ts step() uses ?? null cast to bypass the non-optional statePool contract");
L.push("");
L.push("**File:** " + B + "src/solver/analog/analog-engine.ts" + B + "  ");
L.push("**Lines:** 249, 288, 361");
L.push("");
L.push("**Rule violated:** Rules — No fallbacks. No backwards compatibility shims.");
L.push("");
L.push("The " + B + "ConcreteCompiledAnalogCircuit" + B + " interface in the same file (line 52) declares " + B + "readonly statePool: StatePool" + B + " as non-optional. Yet every access in " + B + "step()" + B + " casts to " + B + "CompiledWithBridges" + B + " and applies " + B + "?? null" + B + ":");
L.push("");
L.push(B+B+B+"typescript");
L.push("const statePool = (this._compiled as CompiledWithBridges).statePool ?? null;");
L.push(B+B+B);
L.push("");
L.push("The cast to the concrete class (where statePool is set via the V3 fallback) allows the null guard to be reached. If the interface contract were enforced, every circuit would have a real pool, the null branch would be unreachable, and the guard is a backwards-compatibility shim. The null path should be removed.");
L.push("");
L.push("**Severity:** Minor");
L.push("");
L.push("---");
L.push("");
L.push("### V5 — MINOR: state-pool.test.ts historical-provenance comment");
L.push("");
L.push("**File:** " + B + "src/solver/analog/__tests__/state-pool.test.ts" + B + "  ");
L.push("**Lines:** 35-37");
L.push("");
L.push("**Rule violated:** Rules — No historical-provenance comments.");
L.push("");
L.push("**Evidence:**");
L.push(B+B+B);
L.push("// Note: checkpoint()/rollback() were removed from StatePool. The engine now");
L.push("// owns a hoisted per-instance checkpoint buffer (see MNAEngine._stateCheckpoint)");
L.push("// so the pool itself is pure state storage. Tests for the old API are deleted.");
L.push(B+B+B);
L.push("");
L.push("Names removed APIs, describes what replaced them, explains the reason for change, and documents deleted tests. All four clauses are historical-provenance content — none explain complicated code to future developers.");
L.push("");
L.push("**Severity:** Minor");
L.push("");
L.push("---");
L.push("");
L.push("### V6 — MINOR: Spec-required StatePool.checkpoint() and StatePool.rollback() methods not implemented");
L.push("");
L.push("**File:** " + B + "src/solver/analog/state-pool.ts" + B);
L.push("");
L.push("**Rule violated:** Completeness — the Phase 6 spec pseudocode refers to " + B + "statePool.checkpoint(simTime)" + B + " and " + B + "statePool.rollback(checkpoint)" + B + " as method calls on the StatePool object. The engine instead inlines equivalent operations directly: " + B + "this._stateCheckpoint.set(statePool.state0)" + B + " and " + B + "statePool.state0.set(this._stateCheckpoint)" + B + ".");
L.push("");
L.push("The Phase 6 gate grep checks pass because the words appear in comments, not method calls. The inlined approach bypasses the " + B + "StateCheckpoint" + B + " interface entirely — the " + B + "simTime" + B + " field is never captured. The spec-defined " + B + "StateCheckpoint" + B + " interface is absent from the codebase.");
L.push("");
L.push("Reported as minor (not critical) because the inlined approach is functionally correct for state0 rollback; however the spec interface contract is formally unfulfilled.");
L.push("");
L.push("**Severity:** Minor");
L.push("");
L.push("---");
L.push("");
L.push("### V7 — MINOR: Capacitor stateSize is 5 (spec: 3); inductor stateSize is 4 (spec: 3)");
L.push("");
L.push("**File:** " + B + "src/components/passives/capacitor.ts" + B + " line 152; " + B + "src/components/passives/inductor.ts" + B + " line 166");
L.push("");
L.push("**Rule violated:** Spec adherence — Phase 5 gate slot table specifies stateSize 3 for both capacitor (GEQ, IEQ, V_PREV) and inductor (GEQ, IEQ, I_PREV). Implementations use stateSize 5 (capacitor: adds SLOT_I_PREV, SLOT_I_PREV_PREV) and stateSize 4 (inductor: adds SLOT_I_PREV_PREV). The extra slots support " + B + "getLteEstimate" + B + " LTE history introduced in Wave 6.1 but the spec slot table was never updated.");
L.push("");
L.push("**Evidence:**");
L.push(B+B+B+"typescript");
L.push("readonly stateSize: number = 5;   // capacitor.ts line 152 -- spec says 3");
L.push("readonly stateSize: number = 4;   // inductor.ts line 166 -- spec says 3");
L.push(B+B+B);
L.push("");
L.push("**Severity:** Minor");
L.push("");
L.push("---");
L.push("");
L.push("## Gaps");
L.push("");
L.push("### G1 — W6T2: No test exercises the NR retry rollback path");
L.push("");
L.push("**Spec requirement (Phase 6 gate / Test Strategy):**");
L.push("> 'Circuit with NR retry path: confirm rollback() is called and state0 is restored.'");
L.push("> 'Trigger an NR failure + retry path and confirm rollback restores state0.'");
L.push("");
L.push("**What was found:** All 6 tests in " + B + "convergence-regression.test.ts" + B + " exercise happy-path convergence only. None force a convergence failure (e.g. by setting " + B + "maxIterations: 1" + B + " to guarantee NR non-convergence), then verify that " + B + "state0" + B + " is restored to checkpoint values before the re-stamp. The rollback path in " + B + "analog-engine.ts" + B + " lines 285-319 is entirely untested by W6T2.");
L.push("");
L.push("**File:** " + B + "src/solver/analog/__tests__/convergence-regression.test.ts" + B);
L.push("");
L.push("---");
L.push("");
L.push("### G2 — W6T2: No test exercises the LTE rejection path or verifies rollback on LTE retry");
L.push("");
L.push("**Spec requirement (Phase 6 gate):** The spec pseudocode shows the LTE rejection path calling " + B + "statePool.rollback(checkpoint)" + B + " before retrying. No test in " + B + "convergence-regression.test.ts" + B + " exercises this path.");
L.push("");
L.push("**What was found:** The 6 tests cover: diode DC convergence, RC transient stability, state0 contents after DC op, state1 update after accepted step, 100-step stability, and reset. None configure a circuit that triggers LTE rejection (e.g. tight trtol or chargeTol) and verifies that state0 is rolled back before the retry NR solve.");
L.push("");
L.push("**File:** " + B + "src/solver/analog/__tests__/convergence-regression.test.ts" + B);
L.push("");
L.push("---");
L.push("");
L.push("### G3 — state-pool.ts missing checkpoint() / rollback() methods and StateCheckpoint interface");
L.push("");
L.push("**Spec requirement:** The spec (section 'StatePool class') defines:");
L.push(B+B+B+"typescript");
L.push("checkpoint(simTime: number): StateCheckpoint;");
L.push("rollback(cp: StateCheckpoint): void;");
L.push("");
L.push("interface StateCheckpoint {");
L.push("  readonly state0: Float64Array;");
L.push("  readonly simTime: number;");
L.push("}");
L.push(B+B+B);
L.push("");
L.push("**What was found:** " + B + "state-pool.ts" + B + " exports only " + B + "StatePool" + B + " with " + B + "acceptTimestep()" + B + " and " + B + "reset()" + B + ". Neither " + B + "checkpoint()" + B + ", " + B + "rollback()" + B + ", nor the " + B + "StateCheckpoint" + B + " interface appear anywhere in the codebase. The " + B + "simTime" + B + " field is never captured.");
L.push("");
L.push("**File:** " + B + "src/solver/analog/state-pool.ts" + B);
L.push("");
L.push("---");
L.push("");
L.push("## Weak Tests");
L.push("");
L.push("### WT1 — RC circuit test has trivially true simTime assertion and loose voltage band");
L.push("");
L.push("**Test path:** " + B + "src/solver/analog/__tests__/convergence-regression.test.ts::convergence regression::RC circuit runs transient steps stably with capacitor near Vs" + B + "  ");
L.push("**Lines:** 158-164");
L.push("");
L.push("**Problem:** The assertions include:");
L.push(B+B+B+"typescript");
L.push("expect(engine.simTime).toBeGreaterThan(0);   // trivially true if any step runs");
L.push("expect(v2).toBeGreaterThan(4.5);             // 10% lower bound");
L.push("expect(v2).toBeLessThanOrEqual(5.01);        // loose upper bound");
L.push(B+B+B);
L.push("");
L.push(B + "expect(engine.simTime).toBeGreaterThan(0)" + B + " is trivially true the moment any step runs. The 10% voltage band passes even with significant drift. The tight-tolerance RC test in " + B + "mna-end-to-end.test.ts::rc_steady_state_no_drift" + B + " already checks driftPct < 0.1%. This test adds no W6T2-specific coverage.");
L.push("");
L.push("---");
L.push("");
L.push("### WT2 — 100-step stability test makes no pool state assertions");
L.push("");
L.push("**Test path:** " + B + "src/solver/analog/__tests__/convergence-regression.test.ts::convergence regression::diode circuit runs 100 transient steps without error" + B + "  ");
L.push("**Lines:** 231-250");
L.push("");
L.push("**Problem:** Verifies only that the engine does not crash and voltages remain within a wide band (v2 > 0.4, v2 < 1.0, v1 to 1 decimal place). Makes no assertion about state0 slot values at any accepted step, acceptTimestep() history shifting, or rollback correctness. None of the behaviors specific to W6T2 are covered.");
L.push("");
L.push("**Evidence:**");
L.push(B+B+B+"typescript");
L.push("expect(engine.getState()).not.toBe(EngineState.ERROR);");
L.push("expect(engine.simTime).toBeGreaterThan(0);");
L.push("expect(v1).toBeCloseTo(5.0, 1);     // 0.1V tolerance");
L.push("expect(v2).toBeGreaterThan(0.4);    // very loose");
L.push("expect(v2).toBeLessThan(1.0);       // very loose");
L.push(B+B+B);
L.push("");
L.push("---");
L.push("");
L.push("### WT3 — acceptTimestep test captures state0 value but never asserts it was shifted to state1");
L.push("");
L.push("**Test path:** " + B + "src/solver/analog/__tests__/convergence-regression.test.ts::convergence regression::statePool state1 is updated after accepted transient step" + B + "  ");
L.push("**Lines:** 201-224");
L.push("");
L.push("**Problem:** " + B + "state0VdBeforeStep" + B + " is captured at line 213 but never referenced in any assertion. The post-step check only verifies the value is in the forward-voltage range — which passes whether or not " + B + "acceptTimestep()" + B + " was called. The test should assert " + B + "state1[diodeBase + 0]" + B + " equals " + B + "state0VdBeforeStep" + B + ". As written, the captured variable is dead code.");
L.push("");
L.push("**Evidence:**");
L.push(B+B+B+"typescript");
L.push("const state0VdBeforeStep = pool.state0[diodeBase + 0];  // captured -- never asserted");
L.push("// ... engine.step() ...");
L.push("const state1VdAfterStep = pool.state1[diodeBase + 0];");
L.push("// MISSING: expect(state1VdAfterStep).toBeCloseTo(state0VdBeforeStep, ...)");
L.push("expect(state1VdAfterStep).toBeGreaterThan(0.5);   // same range as initial DC op");
L.push("expect(state1VdAfterStep).toBeLessThan(0.8);");
L.push(B+B+B);
L.push("");
L.push("---");
L.push("");
L.push("## Legacy References");
L.push("");
L.push("### LR1 — analog-engine.ts line 87: quotes removed API name StatePool.checkpoint()");
L.push("");
L.push("**File:** " + B + "src/solver/analog/analog-engine.ts" + B + "  ");
L.push("**Line:** 87");
L.push("");
L.push("**Quoted evidence:**");
L.push(B+B+B);
L.push("// " + B + "_stateCheckpoint" + B + " replaces the old " + B + "StatePool.checkpoint()" + B + " allocation:");
L.push(B+B+B);
L.push("");
L.push("Names a removed API by its former name. Banned historical-provenance reference.");
L.push("");
L.push("---");
L.push("");
L.push("### LR2 — analog-engine.ts line 352: 'the legacy r variable'");
L.push("");
L.push("**File:** " + B + "src/solver/analog/analog-engine.ts" + B + "  ");
L.push("**Line:** 352");
L.push("");
L.push("**Quoted evidence:**");
L.push(B+B+B);
L.push("// convert to the legacy " + B + "r" + B + " variable (r >= 1 = accept) so the existing");
L.push(B+B+B);
L.push("");
L.push("Names a variable as 'legacy' and explains that old code is preserved to avoid changing other paths. Banned historical-provenance reference.");
L.push("");
L.push("---");
L.push("");
L.push("### LR3 — state-pool.test.ts lines 35-37: removed-API provenance comment");
L.push("");
L.push("**File:** " + B + "src/solver/analog/__tests__/state-pool.test.ts" + B + "  ");
L.push("**Lines:** 35-37");
L.push("");
L.push("**Quoted evidence:**");
L.push(B+B+B);
L.push("// Note: checkpoint()/rollback() were removed from StatePool. The engine now");
L.push("// owns a hoisted per-instance checkpoint buffer (see MNAEngine._stateCheckpoint)");
L.push("// so the pool itself is pure state storage. Tests for the old API are deleted.");
L.push(B+B+B);
L.push("");
L.push("Names removed methods, describes what replaced them, and documents deleted tests. Three independent historical-provenance references in one block.");
L.push("");
L.push("---");
L.push("");
L.push("### LR4 — compiled-analog-circuit.ts lines 89-90: 'Replaces elementPinVertices' / 'coexists' (Wave 6.1 LR1/LR2 — not remediated)");
L.push("");
L.push("**File:** " + B + "src/solver/analog/compiled-analog-circuit.ts" + B + "  ");
L.push("**Lines:** 89-90");
L.push("");
L.push("**Quoted evidence (from Wave 6.1 review, confirmed still present):**");
L.push(B+B+B);
L.push(" *  Replaces elementPinVertices -- carries label, vertex, nodeId in one object.");
L.push(" *  During migration, coexists with elementPinVertices. */");
L.push(B+B+B);
L.push("");
L.push("Flagged as LR1 and LR2 in the Wave 6.1 review. Not recorded as remediated in " + B + "progress.md" + B + ". " + B + "elementPinVertices" + B + " remains present in the file, confirming the migration is still incomplete.");
L.push("");
L.push("---");
L.push("");
L.push("## Hidden Bug Investigation: LTE History Slots on NR Retry Rollback");
L.push("");
L.push("**Assignment:** Determine whether rollback on NR retry or LTE rejection accidentally clobbers SLOT_I_PREV/SLOT_I_PREV_PREV with stale values that corrupt history for subsequent retries.");
L.push("");
L.push("### Finding: No hidden bug — checkpoint timing is correct");
L.push("");
L.push("Both capacitor (" + B + "stampCompanion" + B + " lines 200-223) and inductor (" + B + "stampCompanion" + B + " lines 217-231) write SLOT_I_PREV and SLOT_I_PREV_PREV into " + B + "state0" + B + " during the stamp call.");
L.push("");
L.push("The engine checkpoint is taken at " + B + "analog-engine.ts" + B + " lines 252-254, **before** any " + B + "stampCompanion" + B + " call (companions are stamped at lines 260-264). The checkpoint therefore always captures pre-stamp history slots — i.e., values from the last accepted step.");
L.push("");
L.push("**NR retry execution trace:**");
L.push("1. Line 253: " + B + "_stateCheckpoint.set(statePool.state0)" + B + " — snapshot includes unmodified SLOT_I_PREV from accepted history.");
L.push("2. Line 263: " + B + "stampCompanion(dt, ...)" + B + " — overwrites SLOT_I_PREV and SLOT_I_PREV_PREV with current-step attempt values.");
L.push("3. NR fails.");
L.push("4. Line 289: " + B + "statePool.state0.set(this._stateCheckpoint)" + B + " — restores SLOT_I_PREV and SLOT_I_PREV_PREV to pre-stamp values. Correct.");
L.push("5. Line 295: " + B + "stampCompanion(retryDt, ...)" + B + " — reads SLOT_I_PREV from restored snapshot, consistent with restored " + B + "_prevVoltages" + B + ".");
L.push("");
L.push("**LTE rejection execution trace:** Same analysis applies. Checkpoint taken before first " + B + "stampCompanion" + B + ", so rollback at line 362 restores pre-attempt history. Re-stamp at line 368 reads correct history.");
L.push("");
L.push("**Conclusion:** The pattern is correct. The invariant that makes it work is that " + B + "_stateCheckpoint.set(statePool.state0)" + B + " is always called before " + B + "stampCompanion" + B + ". If this ordering were ever reversed — checkpoint taken after stamp — the history slots would be corrupted on rollback. The ordering must be preserved in any future refactoring.");
L.push("");
L.push("---");
L.push("");
L.push("## Wave 6.1 Follow-up Re-verification");
L.push("");
L.push("| Finding | Status |");
L.push("|---------|--------|");
L.push("| V2 + G3: LTE retry NR failure emits diagnostic + ERROR | **Fixed.** " + B + "analog-engine.ts" + B + " lines 389-405 confirm the " + B + "convergence-failed" + B + " diagnostic and " + B + "EngineState.ERROR" + B + " transition. |");
L.push("| G1: " + B + "analog-engine-interface.test.ts" + B + " includes " + B + "statePool" + B + " field | **Fixed.** Test lines 88-92 include " + B + "statePool: { state0, state1, state2 }" + B + " in the literal. |");
L.push("| V1: init() slot allocation shim replaced with throw | **Fixed per user acceptance.** Lines 181-189 throw on " + B + "stateBaseOffset < 0" + B + ". New surrounding comments (lines 163-175) introduce new violations flagged as V1/LR1 above. |");
L.push("| V3: Historical-provenance comment in " + B + "compiled-analog-circuit.ts" + B + " lines 89-90 | **Not remediated.** Still present (flagged as LR4 above). |");
L.push("| V5: " + B + "ConcreteCompiledAnalogCircuit" + B + " optional statePool fallback | **Not remediated.** " + B + "?? new StatePool(0)" + B + " at line 150 remains (flagged as V3 above). |");
fs.writeFileSync("C:/local_working_projects/digital_in_browser/spec/reviews/phase-6.md", L.join("\n"), "utf8");
console.log("Written phase-6.md, " + L.length + " lines");
