import pathlib

lines = []
lines.append("# Review Report: Wave 6.1 (G1, W6T1, W6T3)")
lines.append("")
lines.append("## Summary")
lines.append("")
lines.append("| Item | Value |")
lines.append("|------|-------|")
lines.append("| Tasks reviewed | 3 (G1, W6T1, W6T3) |")
lines.append("| Violations | 5 (1 critical, 2 major, 2 minor) |")
lines.append("| Gaps | 3 |")
lines.append("| Weak tests | 2 |")
lines.append("| Legacy references | 2 |")
lines.append("| Verdict | **has-violations** |")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Violations")
lines.append("")
lines.append("### V1 — CRITICAL: Engine `init()` performs slot allocation that the spec assigns exclusively to the compiler")
lines.append("")
lines.append("**File:** `src/solver/analog/analog-engine.ts`")
lines.append("**Lines:** 135-152")
lines.append("")
lines.append("**Rule violated:** Completeness rules — the spec (Phase 1 migration plan, slot allocation section) states explicitly: slot allocation happens at compile time in `compiler.ts`. The Phase 6 spec states the `statePool` arrives on the compiled circuit fully allocated. The engine `init()` is responsible only for calling `initState` on each element; it must not modify `stateBaseOffset`. The code at lines 135-152 silently re-allocates `stateBaseOffset` for elements where it is still -1, which is a backwards-compatibility shim that masks compiler omissions.")
lines.append("")
lines.append("**Evidence (lines 135-152):**")
lines.append("```")
lines.append("// Assign stateBaseOffset for elements that were not compiler-processed")
lines.append("// (stateSize > 0 but stateBaseOffset still -1). Then call initState on all")
lines.append("// pool-backed elements to bind them to the state pool.")
lines.append("const cac = compiled as CompiledWithBridges;")
lines.append("if (cac.statePool) {")
lines.append("  let nextOffset = 0;")
lines.append("  for (const el of elements) {")
lines.append("    if (el.stateSize > 0) {")
lines.append("      if (el.stateBaseOffset < 0) {")
lines.append("        el.stateBaseOffset = nextOffset;")
lines.append("      }")
lines.append("      nextOffset = el.stateBaseOffset + el.stateSize;")
lines.append("      if (el.initState) {")
lines.append("        el.initState(cac.statePool);")
lines.append("      }")
lines.append("    }")
lines.append("  }")
lines.append("}")
lines.append("```")
lines.append("")
lines.append("The comment at lines 135-136 admits the intent: 'elements that were not compiler-processed' with 'stateBaseOffset still -1'. Under the rules, a justification comment next to a rule violation makes it worse, not better — it is proof the agent knowingly broke the rule. If an element arrives at engine init with stateBaseOffset -1 and stateSize > 0, that is a compiler bug that must be surfaced as a hard failure, not silently papered over.")
lines.append("")
lines.append("**Severity:** Critical")
lines.append("")
lines.append("---")
lines.append("")
lines.append("### V2 — MAJOR: LTE rejection path calls `acceptTimestep()` unconditionally even when retry NR fails")
lines.append("")
lines.append("**File:** `src/solver/analog/analog-engine.ts`")
lines.append("**Lines:** 297-328")
lines.append("")
lines.append("**Rule violated:** Completeness — the spec pseudocode for `step()` in Phase 6 shows `acceptTimestep()` called only on timestep acceptance. The current code calls `statePool.acceptTimestep()` at line 328 unconditionally regardless of whether the LTE retry converged. This corrupts `state1` and `state2` with state0 from a failed retry, destroying the integration history for subsequent BDF steps.")
lines.append("")
lines.append("**Evidence:**")
lines.append("```")
lines.append("if (this._timestep.shouldReject(r)) {")
lines.append("  this._voltages.set(this._prevVoltages);")
lines.append("  if (statePool && checkpoint) statePool.rollback(checkpoint);")
lines.append("  const rejectedDt = this._timestep.reject();")
lines.append("  // ... re-stamp and retry ...")
lines.append("  const retryResult = newtonRaphson({ ... });")
lines.append("  if (retryResult.converged) {")
lines.append("    this._voltages.set(retryResult.voltages);")
lines.append("    dt = rejectedDt;")
lines.append("  }")
lines.append("  // when NOT converged: falls through with no error, no return")
lines.append("}")
lines.append("")
lines.append("// line 328 -- always reached, even on LTE retry NR failure")
lines.append("if (statePool) statePool.acceptTimestep();")
lines.append("```")
lines.append("")
lines.append("**Severity:** Major")
lines.append("")
lines.append("---")
lines.append("")
lines.append("### V3 — MAJOR: Historical-provenance comments in `compiled-analog-circuit.ts`")
lines.append("")
lines.append("**File:** `src/solver/analog/compiled-analog-circuit.ts`")
lines.append("**Lines:** 89-90")
lines.append("")
lines.append("**Rule violated:** Rules — 'No historical-provenance comments. Any comment describing what code replaced, what it used to do, why it changed, or where it came from is banned.'")
lines.append("")
lines.append("**Evidence:**")
lines.append("```")
lines.append(" *  Replaces elementPinVertices -- carries label, vertex, nodeId in one object.")
lines.append(" *  During migration, coexists with elementPinVertices. */")
lines.append("```")
lines.append("")
lines.append("'Replaces elementPinVertices' names the symbol that was replaced. 'During migration, coexists with elementPinVertices' describes an in-progress migration where old and new patterns are kept alive simultaneously. Both phrases are textbook historical-provenance comments, explicitly banned. The old field `elementPinVertices` is confirmed still present at line 86, validating that the migration is incomplete.")
lines.append("")
lines.append("**Severity:** Major")
lines.append("")
lines.append("---")
lines.append("")
lines.append("### V4 — MINOR: Workaround justification comment in `analog-engine.ts` `init()` (companion to V1)")
lines.append("")
lines.append("**File:** `src/solver/analog/analog-engine.ts`")
lines.append("**Lines:** 135-137")
lines.append("")
lines.append("**Rule violated:** Rules — 'No historical-provenance comments.' The comment explicitly names the class of shortcut being taken ('elements that were not compiler-processed', 'stateBaseOffset still -1'). Reported separately from the code violation (V1) because the comment is independently banned.")
lines.append("")
lines.append("**Evidence:**")
lines.append("```")
lines.append("// Assign stateBaseOffset for elements that were not compiler-processed")
lines.append("// (stateSize > 0 but stateBaseOffset still -1). Then call initState on all")
lines.append("// pool-backed elements to bind them to the state pool.")
lines.append("```")
lines.append("")
lines.append("**Severity:** Minor")
lines.append("")
lines.append("---")
lines.append("")
lines.append("### V5 — MINOR: `ConcreteCompiledAnalogCircuit` constructor accepts `statePool` as optional with silent fallback")
lines.append("")
lines.append("**File:** `src/solver/analog/compiled-analog-circuit.ts`")
lines.append("**Lines:** 133, 150")
lines.append("")
lines.append("**Rule violated:** Rules — 'No fallbacks. No backwards compatibility shims.' The spec requires every compiled circuit to have a properly allocated state pool. An empty `new StatePool(0)` fallback silently masks absent pool allocation.")
lines.append("")
lines.append("**Evidence:**")
lines.append("```")
lines.append("statePool?: StatePool;                                    // line 133 -- optional param")
lines.append("// ...")
lines.append("this.statePool = params.statePool ?? new StatePool(0);   // line 150 -- silent fallback")
lines.append("```")
lines.append("")
lines.append("**Severity:** Minor")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Gaps")
lines.append("")
lines.append("### G1 — `compiled_analog_extends_compiled` test does not include the new `statePool` field")
lines.append("")
lines.append("**Spec requirement:** G1 added `readonly statePool: StatePoolRef` as a required (non-optional) field to `CompiledAnalogCircuit` in `src/core/analog-engine-interface.ts` (confirmed at line 104). The test `compiled_analog_extends_compiled` in `src/core/__tests__/analog-engine-interface.test.ts` (lines 77-98) constructs a `CompiledAnalogCircuit` literal without `statePool`. Since the interface declares `readonly statePool: StatePoolRef` without `?`, this literal is type-invalid and would fail TypeScript compilation. The test was not updated when G1 was implemented.")
lines.append("")
lines.append("**What was found:**")
lines.append("```")
lines.append("const compiled: CompiledAnalogCircuit = {")
lines.append("  netCount: 5, componentCount: 3, nodeCount: 4, elementCount: 3,")
lines.append("  labelToNodeId: new Map([[\"R1\", 1], [\"R2\", 2]]),")
lines.append("  wireToNodeId: new Map(),")
lines.append("  // statePool: absent")
lines.append("};")
lines.append("```")
lines.append("")
lines.append("**File:** `src/core/__tests__/analog-engine-interface.test.ts` lines 77-98")
lines.append("")
lines.append("---")
lines.append("")
lines.append("### G2 — No W6T1 behavioural tests for checkpoint/rollback/acceptTimestep in engine test suite")
lines.append("")
lines.append("**Spec requirement (Phase 6 gate + Test Strategy):** The spec mandates smoke tests verifying:")
lines.append("- `statePool.reset()` is called in `reset()` and `dcOperatingPoint()`")
lines.append("- `state1`/`state2` are initialised from `state0` after DC convergence")
lines.append("- Checkpoint is taken before NR; rollback restores `state0` on NR failure")
lines.append("- `acceptTimestep()` is called after an accepted timestep")
lines.append("- A circuit exercising the NR retry path confirms rollback is called and `state0` is restored")
lines.append("")
lines.append("**What was found:** `src/solver/analog/__tests__/analog-engine.test.ts` has no assertions that inspect `statePool` state at any point. The strings 'checkpoint', 'rollback', 'acceptTimestep', 'state1', 'state2' do not appear in the test file. The pool-state machinery introduced by W6T1 is entirely untested.")
lines.append("")
lines.append("**File:** `src/solver/analog/__tests__/analog-engine.test.ts`")
lines.append("")
lines.append("---")
lines.append("")
lines.append("### G3 — LTE retry NR failure is silently unhandled (incomplete `step()` implementation)")
lines.append("")
lines.append("**Spec requirement (Phase 6 pseudocode):** The spec shows the LTE rejection path retrying with smaller dt. The NR convergence failure path (lines 268-286) transitions to `EngineState.ERROR` on unrecoverable failure. The LTE retry path is missing equivalent error handling.")
lines.append("")
lines.append("**What was found:** Lines 310-328: when `retryResult.converged` is false, no diagnostic is emitted, no `EngineState.ERROR` transition occurs. Execution falls through to `statePool.acceptTimestep()` and `this._simTime += dt` with the original (non-corrected) `dt`, silently advancing simulation on a bad solution.")
lines.append("")
lines.append("**File:** `src/solver/analog/analog-engine.ts` lines 310-328")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Weak Tests")
lines.append("")
lines.append("### WT1 — `transient_rc_decay` asserts only that simulation did not crash")
lines.append("")
lines.append("**Test path:** `src/solver/analog/__tests__/analog-engine.test.ts::MNAEngine::transient_rc_decay`")
lines.append("")
lines.append("**Problem:** The test comment at lines 243-251 explicitly states: 'For a true RC discharge we'd need Vs switched off. Here we verify the simulation runs stably and simTime advances.' The assertions `expect(engine.simTime).toBeGreaterThan(0)` and `expect(steps).toBeGreaterThan(0)` are trivially true as long as the engine does not crash. The voltage range check is a loose band. No assertion verifies any pool state, checkpoint, or rollback behavior relevant to W6T1.")
lines.append("")
lines.append("**Evidence:**")
lines.append("```")
lines.append("expect(engine.simTime).toBeGreaterThan(0);   // trivially true if engine runs at all")
lines.append("expect(steps).toBeGreaterThan(0);            // trivially true if engine runs at all")
lines.append("const v2 = engine.getNodeVoltage(2);")
lines.append("expect(v2).toBeGreaterThan(4.5);             // loose range, not spec-tied value")
lines.append("expect(v2).toBeLessThanOrEqual(5.01);")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")
lines.append("### WT2 — `reset_clears_state` does not assert `statePool.state0` was zeroed")
lines.append("")
lines.append("**Test path:** `src/solver/analog/__tests__/analog-engine.test.ts::MNAEngine::reset_clears_state`")
lines.append("")
lines.append("**Problem:** The spec requires `statePool.reset()` to be called inside `reset()`. This is the primary W6T1 behavior for `reset()`. The test verifies `simTime`, node voltages, and `engineState` but makes no assertion about `statePool.state0` (or any pool vector) after reset. The pool reset behavior tested by W6T1 is absent.")
lines.append("")
lines.append("**Evidence:**")
lines.append("```")
lines.append("engine.reset();")
lines.append("expect(engine.simTime).toBe(0);")
lines.append("expect(engine.getNodeVoltage(1)).toBe(0);")
lines.append("expect(engine.getNodeVoltage(2)).toBe(0);")
lines.append("expect(engine.getState()).toBe(EngineState.STOPPED);")
lines.append("// statePool.state0 contents not checked")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Legacy References")
lines.append("")
lines.append("### LR1 — `compiled-analog-circuit.ts` line 89: 'Replaces elementPinVertices'")
lines.append("")
lines.append("**File:** `src/solver/analog/compiled-analog-circuit.ts`")
lines.append("**Line:** 89")
lines.append("")
lines.append("**Quoted evidence:**")
lines.append("```")
lines.append(" *  Replaces elementPinVertices -- carries label, vertex, nodeId in one object.")
lines.append("```")
lines.append("")
lines.append("Names the symbol that was replaced. Banned historical-provenance reference to a replaced API.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("### LR2 — `compiled-analog-circuit.ts` line 90: 'During migration, coexists with elementPinVertices'")
lines.append("")
lines.append("**File:** `src/solver/analog/compiled-analog-circuit.ts`")
lines.append("**Line:** 90")
lines.append("")
lines.append("**Quoted evidence:**")
lines.append("```")
lines.append(" *  During migration, coexists with elementPinVertices. */")
lines.append("```")
lines.append("")
lines.append("Describes an ongoing migration and explicit coexistence of old and new fields. The old field `elementPinVertices` is confirmed still present at line 86, confirming the migration is incomplete. This is a banned historical-provenance reference and a signal that old code has not been removed.")

out = pathlib.Path("C:/local_working_projects/digital_in_browser/spec/reviews/wave-6.1.md")
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Written {out} ({out.stat().st_size} bytes)")
