/**
 * Probe test: inspect ngspice-side raw topology + elementStates for a
 * capacitor and inductor circuit, both via NgspiceBridge directly and
 * via ComparisonSession (the path consumed by the MCP
 * `harness_get_attempt` tool).
 *
 * These tests verify that the patched ngspice DLL populates the device
 * state slots (CAPqcap/CAPccap, INDflux) and that the TS bridge surfaces
 * them in CaptureSession.elementStates AND through ComparisonSession.getAttempt.
 */
import { describe, it, expect } from "vitest";
import { resolve } from "node:path";
import { accessSync } from "node:fs";
import { NgspiceBridge } from "./ngspice-bridge.js";
import { ComparisonSession } from "./comparison-session.js";

const DLL_PATH = resolve(
  process.cwd(),
  "ref/ngspice/visualc-shared/x64/Release/bin/spice.dll",
);
let _dllAvailable: boolean | null = null;
function dllAvailable(): boolean {
  if (_dllAvailable !== null) return _dllAvailable;
  try { accessSync(DLL_PATH); _dllAvailable = true; }
  catch { _dllAvailable = false; }
  return _dllAvailable;
}
const describeIfDll = dllAvailable() ? describe : describe.skip;

describeIfDll("ngspice cap/ind state probe — direct bridge", () => {
  it("RC transient: ngspice elementStates has Q and CCAP on C1", async () => {
    const bridge = new NgspiceBridge(DLL_PATH);
    await bridge.init();
    const netlist = [
      "* RC transient",
      "Vs 1 0 DC 5",
      "R1 1 2 1k",
      "C1 2 0 1u",
      ".tran 1e-5 1e-3 UIC",
      ".end",
    ].join("\n");
    bridge.loadNetlist(netlist);
    bridge.runTran("1m", "10u");

    const session = bridge.getCaptureSession();
    expect(session.steps.length).toBeGreaterThan(0);

    const step = session.steps[Math.min(3, session.steps.length - 1)]!;
    const acc = step.attempts[step.acceptedAttemptIndex];
    expect(acc).toBeDefined();
    expect(acc!.iterations.length).toBeGreaterThan(0);
    const iter = acc!.iterations[acc!.iterations.length - 1]!;
    const capEs = iter.elementStates.find((es) => es.label.toUpperCase() === "C1");
    expect(capEs, "C1 element state must be present on ngspice side").toBeDefined();
    expect(capEs!.slots.Q, "C1 must expose Q slot").toBeDefined();
    expect(capEs!.slots.CCAP, "C1 must expose CCAP slot").toBeDefined();
  }, 60_000);

  it("RL transient: ngspice elementStates has PHI on L1", async () => {
    const bridge = new NgspiceBridge(DLL_PATH);
    await bridge.init();
    const netlist = [
      "* RL transient",
      "Vs 1 0 DC 5",
      "R1 1 2 1",
      "L1 2 0 1m",
      ".tran 1e-5 1e-3 UIC",
      ".end",
    ].join("\n");
    bridge.loadNetlist(netlist);
    bridge.runTran("1m", "10u");

    const session = bridge.getCaptureSession();
    expect(session.steps.length).toBeGreaterThan(0);

    const step = session.steps[Math.min(3, session.steps.length - 1)]!;
    const acc = step.attempts[step.acceptedAttemptIndex];
    expect(acc).toBeDefined();
    const iter = acc!.iterations[acc!.iterations.length - 1]!;
    const indEs = iter.elementStates.find((es) => es.label.toUpperCase() === "L1");
    expect(indEs, "L1 element state must be present on ngspice side").toBeDefined();
    expect(indEs!.slots.PHI, "L1 must expose PHI slot").toBeDefined();
  }, 60_000);
});

describeIfDll("ngspice cap state probe — via ComparisonSession", () => {
  it("rc-step.dts: ComparisonSession.ngspiceSession exposes Q/CCAP on capacitor", async () => {
    const session = new ComparisonSession({
      dtsPath: resolve(process.cwd(), "tmp-hang-circuits/rc-step.dts"),
      dllPath: DLL_PATH,
      maxOurSteps: 20,
    });
    await session.init();
    await session.runTransient(0, 5e-3, 1e-4);

    // eslint-disable-next-line no-console
    console.log("CIR (SPICE netlist) generated by ComparisonSession:");
    // eslint-disable-next-line no-console
    console.log((session as any)._cirClean ?? "(none)");

    // eslint-disable-next-line no-console
    console.log("NGSPICE session topology elements:");
    for (const el of session.ngspiceSession!.topology.elements) {
      // eslint-disable-next-line no-console
      console.log(`  label=${el.label} typeId=${el.type}`);
    }

    const ngSteps = session.ngspiceSession!.steps;
    expect(ngSteps.length).toBeGreaterThan(0);

    // Pick a transient step with accepted iterations.
    const tran = ngSteps.find(
      (s) =>
        (s.analysisPhase === "tranFloat" || s.analysisPhase === "tranInit") &&
        s.attempts[s.acceptedAttemptIndex] &&
        s.attempts[s.acceptedAttemptIndex]!.iterations.length > 0,
    );
    expect(tran, "expected a transient step with accepted iterations").toBeDefined();
    const acc = tran!.attempts[tran!.acceptedAttemptIndex]!;
    const iter = acc.iterations[acc.iterations.length - 1]!;

    // eslint-disable-next-line no-console
    console.log(`NGSPICE (via ComparisonSession) step t=${tran!.stepStartTime} elementStates:`);
    for (const es of iter.elementStates) {
      // eslint-disable-next-line no-console
      console.log(`  ${es.label} slots=${JSON.stringify(es.slots)}`);
    }

    // The capacitor in rc-step.dts is labeled "Vc" in the .dts file, but the
    // ngspice netlist generator prepends "C" to form a SPICE-legal capacitor
    // instance name ("CVc") because ngspice infers device type from the
    // instance-name prefix. ngspice uppercases it to "CVC".
    const capEs = iter.elementStates.find((es) => es.label.toUpperCase() === "CVC");
    expect(capEs, `expected capacitor labeled CVC in ngspice session; saw: ${iter.elementStates.map(e => e.label).join(",")}`).toBeDefined();
    expect(capEs!.slots.Q, "Vc must expose Q slot").toBeDefined();
    expect(capEs!.slots.CCAP, "Vc must expose CCAP slot").toBeDefined();
  }, 60_000);
});

describeIfDll("ngspice cap/ind state via harness_get_attempt path", () => {
  it("rc-step.dts: getAttempt(tranNR) exposes Q/CCAP on CVC in ngspice elementStates", async () => {
    const session = new ComparisonSession({
      dtsPath: resolve(process.cwd(), "tmp-hang-circuits/rc-step.dts"),
      dllPath: DLL_PATH,
      maxOurSteps: 20,
    });
    await session.init();
    await session.runTransient(0, 5e-3, 1e-4);

    // Walk ngspice steps and find the first one with a tranNR attempt that has
    // iterations. Use that as the canonical MCP-path probe — the exact step
    // index varies per ngspice solver behaviour but the slot exposure contract
    // is step-invariant.
    const ngMap = session.sessionMap().ngspice;
    let probeStepIndex = -1;
    let probePhase: "tranNR" | "tranInit" | null = null;
    for (let i = 0; i < ngMap.steps.length && probeStepIndex < 0; i++) {
      const step = ngMap.steps[i]!;
      for (const att of step.attempts) {
        if ((att.phase === "tranNR" || att.phase === "tranInit") && att.iterationCount > 0) {
          probeStepIndex = i;
          probePhase = att.phase;
          break;
        }
      }
    }
    expect(probeStepIndex, "expected at least one transient NR attempt with iterations").toBeGreaterThanOrEqual(0);
    expect(probePhase, "expected phase to be resolved").not.toBeNull();

    const detail = session.getAttempt({
      stepIndex: probeStepIndex,
      phase: probePhase!,
      phaseAttemptIndex: 0,
    });
    expect(detail.iterations.length, "attempt must have at least one iteration").toBeGreaterThan(0);

    // The paired-iteration array uses Math.max(ourIters.length, ngIters.length);
    // our side may run more NR iterations than ngspice, leaving trailing rows
    // where ngspice is null. Walk back from the end to pick the last row that
    // actually has ngspice data — that is the iteration whose ngspice state
    // we want to probe.
    const ngIter = [...detail.iterations]
      .reverse()
      .find(pair => pair.ngspice !== null);
    expect(ngIter, "at least one paired iteration must have ngspice data").toBeDefined();

    const ngStates = ngIter!.ngspice!.elementStates;
    // eslint-disable-next-line no-console
    console.log(
      `harness_get_attempt path: ngspice elementStates keys = [${Object.keys(ngStates).join(", ")}]`,
    );

    // Labels come from ngspice topology. Accept case-insensitively and match
    // prefix+suffix (ngspice uppercases everything).
    const capKey = Object.keys(ngStates).find(k => k.toUpperCase() === "CVC");
    expect(capKey, `expected capacitor key CVC; saw: ${Object.keys(ngStates).join(",")}`).toBeDefined();
    const capSlots = ngStates[capKey!];
    expect(capSlots.Q, "Vc must expose Q slot via getAttempt").toBeDefined();
    expect(capSlots.CCAP, "Vc must expose CCAP slot via getAttempt").toBeDefined();
    // Sanity: Q = C * V = 1uF * 5V = 5e-6 on the converged step.
    expect(Math.abs(capSlots.Q!)).toBeGreaterThan(0);
  }, 60_000);

  it("RL transient: direct bridge surfaces PHI and NG_VOLT on L1", async () => {
    const bridge = new NgspiceBridge(DLL_PATH);
    await bridge.init();
    const netlist = [
      "* RL transient",
      "Vs 1 0 DC 5",
      "R1 1 2 1",
      "L1 2 0 1m",
      ".tran 1e-5 1e-3 UIC",
      ".end",
    ].join("\n");
    bridge.loadNetlist(netlist);
    bridge.runTran("1m", "10u");

    const session = bridge.getCaptureSession();
    // Walk all steps to find one whose accepted attempt has non-zero PHI.
    let foundPhi = false;
    let foundVoltSlotKey = false;
    for (const step of session.steps) {
      const acc = step.attempts[step.acceptedAttemptIndex];
      if (!acc || acc.iterations.length === 0) continue;
      const iter = acc.iterations[acc.iterations.length - 1]!;
      const indEs = iter.elementStates.find((es) => es.label.toUpperCase() === "L1");
      if (!indEs) continue;
      if (indEs.slots.PHI !== undefined) foundPhi = true;
      if (indEs.slots.NG_VOLT !== undefined) foundVoltSlotKey = true;
      if (foundPhi && foundVoltSlotKey) break;
    }
    expect(foundPhi, "inductor PHI (INDflux) must be surfaced on at least one step").toBe(true);
    expect(foundVoltSlotKey, "inductor NG_VOLT (INDvolt) must be surfaced on at least one step").toBe(true);
  }, 60_000);
});
