/**
 * B3 (strict): E2E surface coverage for the RC zero-crossing LTE path.
 *
 * Single Playwright test: RC series circuit driven by AC at 20 Hz, loaded
 * via sim-load-data (DTS JSON base64), stepped through one full period via
 * batched sim-step + sim-read-all-signals messages, then asserted for
 * zero-crossings and peak amplitude.
 *
 * Circuit topology: R=1kΩ, C=1µF, AC at 20 Hz, 1V amplitude.
 * DTS JSON pre-generated by e2e/scripts/gen-rc-dts.ts and stored at
 * e2e/circuits/rc-ac-20hz.dts.json.
 *
 * No timeout overrides. If the engine stalls, simTime stops advancing,
 * stepCount exhausts, and the assertions fail- that is the finding.
 */
import { test, expect } from '@playwright/test';
import { SimulatorHarness } from '../fixtures/simulator-harness';
import { readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// DTS JSON for a series RC circuit: AcVoltageSource (20 Hz, 1 V) → R(1kΩ) → C(1µF) → Ground.
// Pre-generated by `npx tsx e2e/scripts/gen-rc-dts.ts > e2e/circuits/rc-ac-20hz.dts.json`.
const RC_AC_DTS = readFileSync(resolve(__dirname, '../circuits/rc-ac-20hz.dts.json'), 'utf-8');
const RC_AC_B64 = Buffer.from(RC_AC_DTS, 'utf-8').toString('base64');

// ---------------------------------------------------------------------------

test.describe('RLC LTE path- postMessage (E2E) surface', () => {
  let harness: SimulatorHarness;

  test.beforeEach(async ({ page }) => {
    harness = new SimulatorHarness(page);
    await harness.load();
  });

  test('RC zero-crossing progression through the postMessage bridge', async ({ page }) => {
    // Circuit: R=1kΩ, C=1µF, AC source at 20 Hz, 1 V amplitude.
    // At f=20 Hz << fc≈159 Hz: |Vc/Vs| ≈ 0.992, phase lag ≈ 7.2°.
    // Vc closely tracks the source and must cross zero twice per period.

    await harness.postToSim({ type: 'sim-load-data', data: RC_AC_B64 });
    await harness.waitForMessage('sim-loaded');

    // Stepping strategy: batch N sim-step messages in a single page.evaluate
    // to avoid the per-step round-trip overhead, then send one
    // sim-read-all-signals to collect {signals, simTime}. This reduces
    // Playwright ↔ browser round-trips from O(steps) to O(batches).
    //
    // Period = 50ms at 20Hz. Typical adaptive step ≈ 1µs → ~50k steps/period.
    // Batch size = 500 steps, ~100 batches per period- manageable.
    //
    // If the engine stalls (STOPPED state), simTime freezes and the outer
    // while loop will exhaust batchLimit without reaching 2*period.
    // The assertions on samples.length, crossings, and peak will then fail.

    const period = 1 / 20; // 50 ms sim-time
    const BATCH_SIZE = 500;
    const BATCH_LIMIT = 600; // 600 batches × 500 steps = 300k steps max

    /**
     * Send N sim-step messages in one evaluate call (no await between them),
     * then read-all-signals. Returns { signals, simTime }.
     */
    async function batchStepAndRead(n: number): Promise<{
      signals: Record<string, number>;
      simTime: number | null;
    }> {
      // Fire N sim-step messages synchronously inside the browser
      await page.evaluate((count) => {
        for (let i = 0; i < count; i++) {
          (window as any).__postToSim({ type: 'sim-step' });
        }
        // Drain the pending sim-step response queue (sim-step emits no response)
      }, n);

      // Now request a signal read
      await harness.postToSim({ type: 'sim-read-all-signals' });
      return harness.waitForMessage<{
        signals: Record<string, number>;
        simTime: number | null;
      }>('sim-signals');
    }

    // Phase 1: advance past the first period (startup transient settle)
    let simTime = 0;
    let batchCount = 0;
    while (simTime < period && batchCount < BATCH_LIMIT) {
      const result = await batchStepAndRead(BATCH_SIZE);
      simTime = result.simTime ?? simTime;
      batchCount++;
    }

    // Phase 2: collect samples across the second period (period to 2*period)
    const samples: Array<{ t: number; vc: number }> = [];
    batchCount = 0;
    while (simTime < 2 * period && batchCount < BATCH_LIMIT) {
      const result = await batchStepAndRead(BATCH_SIZE);
      const t = result.simTime ?? simTime;
      const vc = result.signals['Vc:pos'] ?? 0;
      simTime = t;
      samples.push({ t, vc });
      batchCount++;
    }

    // Must have collected samples in period 2. If the engine stalled, simTime
    // would not advance past period 1 and samples would be empty.
    expect(samples.length).toBeGreaterThan(0);

    // Count zero-crossings of Vc in the sampled series.
    // With BATCH_SIZE=500 steps, consecutive samples span ~500µs each-
    // well within one half-cycle (25ms at 20Hz), so crossings are detectable.
    let crossings = 0;
    for (let i = 1; i < samples.length; i++) {
      const a = samples[i - 1]!.vc;
      const b = samples[i]!.vc;
      if (a === 0 || b === 0) continue;
      if (Math.sign(a) !== Math.sign(b)) crossings++;
    }

    // At least 2 zero-crossings in one full period
    expect(crossings).toBeGreaterThanOrEqual(2);

    // Peak |Vc| ≥ 0.9 V (analytical: 0.992 V at f/fc = 0.126)
    let peak = 0;
    for (const s of samples) {
      const a = Math.abs(s.vc);
      if (a > peak) peak = a;
    }
    expect(peak).toBeGreaterThanOrEqual(0.9);
  });
});
