/**
 * Mechanically-extracted Falstad/CircuitJS1 reference shapes.
 *
 * Reads fixtures/falstad-shapes.json (generated by scripts/falstad-extract/)
 * and provides draw functions and pin positions for analog component
 * shape comparison — with zero manual transcription.
 *
 * The JSON contains draw calls and pin positions in CircuitJS1 pixel coordinates.
 * This module converts them to grid units (÷16) for comparison with our TS
 * component rendering.
 *
 * To regenerate: bash scripts/falstad-extract/extract.sh
 */

import { readFileSync } from "fs";
import { join } from "path";
// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

interface Point {
  x: number;
  y: number;
}

export interface FalstadPinRef {
  label: string;
  x: number;
  y: number;
}

// ---------------------------------------------------------------------------
// Drawing interface
// ---------------------------------------------------------------------------

export interface RefDrawContext {
  drawLine(x1: number, y1: number, x2: number, y2: number): void;
  drawPolygon(points: readonly Point[], filled: boolean): void;
  drawCircle(cx: number, cy: number, radius: number, filled: boolean): void;
  drawArc(
    cx: number,
    cy: number,
    radius: number,
    startAngle: number,
    endAngle: number,
  ): void;
  drawRect(
    x: number,
    y: number,
    width: number,
    height: number,
    filled: boolean,
  ): void;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const PX_TO_GRID = 1 / 16;

// ---------------------------------------------------------------------------
// JSON types
// ---------------------------------------------------------------------------

interface DrawCall {
  type: string;
  x1?: number; y1?: number; x2?: number; y2?: number;
  thick?: boolean;
  cx?: number; cy?: number; r?: number;
  start?: number; end?: number;
  x?: number; y?: number; w?: number; h?: number;
  points?: [number, number][];
  text?: string;
}

interface ComponentData {
  className: string;
  style: string;
  postCount: number;
  x: number; y: number; x2: number; y2: number;
  pins: Array<{ index: number; x: number; y: number }>;
  draws: DrawCall[];
}

// ---------------------------------------------------------------------------
// CircuitJS1 JSON key → TS registry type name
// ---------------------------------------------------------------------------

const JSON_TO_TS: Record<string, string> = {
  // Passives
  Resistor: "Resistor",
  Capacitor: "Capacitor",
  Inductor: "Inductor",
  Fuse: "Fuse",
  Pot: "Potentiometer",
  Transformer: "Transformer",
  TappedTransformer: "TappedTransformer",
  Crystal: "Crystal",
  Memristor: "Memristor",
  PolarCapacitor: "PolarizedCap",
  TransLine: "TransmissionLine",
  // Semiconductors
  Diode: "Diode",
  Zener: "ZenerDiode",
  LED: "AnalogLED",
  Transistor_NPN: "NpnBJT",
  Transistor_PNP: "PnpBJT",
  Mosfet_NPN: "NMOS",
  Mosfet_PNP: "PMOS",
  Jfet_NPN: "NJFET",
  Jfet_PNP: "PJFET",
  SCR: "SCR",
  Triac: "Triac",
  Diac: "Diac",
  TunnelDiode: "TunnelDiode",
  Varactor: "VaractorDiode",
  Triode: "Triode",
  // Sources
  DCVoltage: "DcVoltageSource",
  ACVoltage: "AcVoltageSource",
  Current: "CurrentSource",
  Ground: "Ground",
  Rail: "VariableRail",
  // Active
  OpAmp: "OpAmp",
  OpAmpReal: "RealOpAmp",
  Comparator: "VoltageComparator",
  Timer: "Timer555",
  OTA: "OTA",
  Optocoupler: "Optocoupler",
  VCVS: "VCVS",
  VCCS: "VCCS",
  CCVS: "CCVS",
  CCCS: "CCCS",
  SchmittInverting: "SchmittInverting",
  SchmittNonInverting: "SchmittNonInverting",
  AnalogSwitch: "AnalogSwitchSPST",
  AnalogSwitch2: "AnalogSwitchSPDT",
  // Sensors
  LDR: "LDR",
  ThermistorNTC: "NTCThermistor",
  SparkGap: "SparkGap",
  Lamp: "AnalogLamp",
};

// Pin labels in CircuitJS1 getPost() index order per TS type.
const PIN_LABELS: Record<string, string[]> = {
  // Passives
  Resistor: ["A", "B"],
  Capacitor: ["pos", "neg"],
  Inductor: ["A", "B"],
  Fuse: ["out1", "out2"],
  Potentiometer: ["A", "B", "W"],
  Transformer: ["P1", "S1", "P2", "S2"],
  TappedTransformer: ["P1", "P2", "S1", "CT", "S2"],
  Crystal: ["A", "B"],
  Memristor: ["A", "B"],
  PolarizedCap: ["pos", "neg"],
  TransmissionLine: ["P1b", "P2b", "P1a", "P2a"],
  // Semiconductors
  Diode: ["A", "K"],
  ZenerDiode: ["A", "K"],
  AnalogLED: ["A", "K"],
  TunnelDiode: ["A", "K"],
  VaractorDiode: ["A", "K"],
  Diac: ["A", "B"],
  NpnBJT: ["B", "C", "E"],
  PnpBJT: ["B", "E", "C"],
  NMOS: ["G", "S", "D"],
  PMOS: ["G", "S", "D"],
  NJFET: ["G", "S", "D"],
  PJFET: ["G", "S", "D"],
  SCR: ["A", "K", "G"],
  Triac: ["MT1", "MT2", "G"],
  Triode: ["P", "G", "K"],
  // Sources
  DcVoltageSource: ["pos", "neg"],
  AcVoltageSource: ["pos", "neg"],
  CurrentSource: ["pos", "neg"],
  Ground: ["gnd"],
  VariableRail: ["pos"],
  // Active
  OpAmp: ["in-", "in+", "out"],
  RealOpAmp: ["in-", "in+", "out", "Vcc+", "Vcc-"],
  VoltageComparator: ["in+", "in-", "out"],
  Timer555: ["VCC", "GND", "TRIG", "THR", "CTRL", "RST", "DIS", "OUT"],
  OTA: ["V+", "V-", "Iabc", "OUT+", "OUT-"],
  Optocoupler: ["anode", "cathode", "collector", "emitter"],
  VCVS: ["ctrl+", "ctrl-", "out+", "out-"],
  VCCS: ["ctrl+", "ctrl-", "out+", "out-"],
  CCVS: ["sense+", "sense-", "out+", "out-"],
  CCCS: ["sense+", "sense-", "out+", "out-"],
  SchmittInverting: ["in", "out"],
  SchmittNonInverting: ["in", "out"],
  AnalogSwitchSPST: ["in", "out", "ctrl"],
  AnalogSwitchSPDT: ["com", "no", "nc", "ctrl"],
  // Sensors
  LDR: ["pos", "neg"],
  NTCThermistor: ["pos", "neg"],
  SparkGap: ["pos", "neg"],
  AnalogLamp: ["A", "B"],
};

// ---------------------------------------------------------------------------
// Replay engine
// ---------------------------------------------------------------------------

function replayDraw(ctx: RefDrawContext, call: DrawCall, g: number): void {
  switch (call.type) {
    case "line":
      ctx.drawLine(call.x1! * g, call.y1! * g, call.x2! * g, call.y2! * g);
      break;
    case "fillPolygon":
      if (call.points) {
        ctx.drawPolygon(
          call.points.map(([x, y]) => ({ x: x * g, y: y * g })),
          true,
        );
      }
      break;
    case "polyline":
      if (call.points && call.points.length >= 2) {
        for (let i = 0; i < call.points.length - 1; i++) {
          ctx.drawLine(
            call.points[i][0] * g, call.points[i][1] * g,
            call.points[i + 1][0] * g, call.points[i + 1][1] * g,
          );
        }
      }
      break;
    case "arc":
      ctx.drawArc(call.cx! * g, call.cy! * g, call.r! * g, call.start!, call.end!);
      break;
    case "fillCircle":
      ctx.drawCircle(call.cx! * g, call.cy! * g, call.r! * g, true);
      break;
    case "rect":
      ctx.drawRect(call.x! * g, call.y! * g, call.w! * g, call.h! * g, false);
      break;
    case "fillRect":
      ctx.drawRect(call.x! * g, call.y! * g, call.w! * g, call.h! * g, true);
      break;
    // text: skip — audit compares geometry not text
  }
}

// ---------------------------------------------------------------------------
// Build maps (lazy, once)
// ---------------------------------------------------------------------------

let _refs: Map<string, (ctx: RefDrawContext) => void> | null = null;
let _pins: Map<string, FalstadPinRef[]> | null = null;

function ensureBuilt(): void {
  if (_refs) return;
  _refs = new Map();
  _pins = new Map();

  const jsonPath = join(__dirname, "../../fixtures/falstad-shapes.json");
  const fixture: Record<string, ComponentData> = JSON.parse(
    readFileSync(jsonPath, "utf-8"),
  );

  for (const [jsonKey, comp] of Object.entries(fixture)) {
    const tsType = JSON_TO_TS[jsonKey];
    if (!tsType) continue;

    // Draw function
    const draws = comp.draws;
    _refs.set(tsType, (ctx: RefDrawContext) => {
      for (const call of draws) {
        replayDraw(ctx, call, PX_TO_GRID);
      }
    });

    // Pin positions
    const labels = PIN_LABELS[tsType];
    _pins.set(
      tsType,
      comp.pins.map((p, i) => ({
        label: labels?.[i] ?? `pin${i}`,
        x: p.x * PX_TO_GRID,
        y: p.y * PX_TO_GRID,
      })),
    );
  }
}

// ---------------------------------------------------------------------------
// Public API — drop-in replacements for falstad-reference.ts exports
// ---------------------------------------------------------------------------

/** Map of TS type → draw function replaying CircuitJS1 draw calls in grid coords. */
export const FALSTAD_REFERENCES: ReadonlyMap<
  string,
  (ctx: RefDrawContext) => void
> = {
  get size() { ensureBuilt(); return _refs!.size; },
  has(key: string) { ensureBuilt(); return _refs!.has(key); },
  get(key: string) { ensureBuilt(); return _refs!.get(key); },
  keys() { ensureBuilt(); return _refs!.keys(); },
  values() { ensureBuilt(); return _refs!.values(); },
  entries() { ensureBuilt(); return _refs!.entries(); },
  forEach(cb: (value: (ctx: RefDrawContext) => void, key: string, map: ReadonlyMap<string, (ctx: RefDrawContext) => void>) => void) {
    ensureBuilt();
    _refs!.forEach((v, k) => cb(v, k, this));
  },
  [Symbol.iterator]() { ensureBuilt(); return _refs![Symbol.iterator](); },
};

/** Map of TS type → expected pin positions (grid coords). */
export const FALSTAD_PIN_POSITIONS: ReadonlyMap<string, FalstadPinRef[]> = {
  get size() { ensureBuilt(); return _pins!.size; },
  has(key: string) { ensureBuilt(); return _pins!.has(key); },
  get(key: string) { ensureBuilt(); return _pins!.get(key); },
  keys() { ensureBuilt(); return _pins!.keys(); },
  values() { ensureBuilt(); return _pins!.values(); },
  entries() { ensureBuilt(); return _pins!.entries(); },
  forEach(cb: (value: FalstadPinRef[], key: string, map: ReadonlyMap<string, FalstadPinRef[]>) => void) {
    ensureBuilt();
    _pins!.forEach((v, k) => cb(v, k, this));
  },
  [Symbol.iterator]() { ensureBuilt(); return _pins![Symbol.iterator](); },
};

// ---------------------------------------------------------------------------
// World-position transform (rotation + mirror)
// ---------------------------------------------------------------------------

/**
 * Compute expected world-space pin position after applying rotation and mirror.
 * Matches the transform order used by our pinWorldPosition():
 *   mirror (negate Y in local space) -> rotate (0/90/180/270) -> translate.
 */
export function falstadWorldPosition(
  localX: number,
  localY: number,
  posX: number,
  posY: number,
  rotation: number,
  mirror: boolean,
): { x: number; y: number } {
  let x = localX;
  let y = localY;

  // Mirror: negate Y (vertical flip), matching Java Digital's convention
  if (mirror) y = -y;

  // Rotate: 0=0deg, 1=90deg, 2=180deg, 3=270deg
  let rx = x;
  let ry = y;
  switch (rotation) {
    case 1: // 90deg CW
      rx = y;
      ry = -x;
      break;
    case 2: // 180deg
      rx = -x;
      ry = -y;
      break;
    case 3: // 270deg CW (= 90deg CCW)
      rx = -y;
      ry = x;
      break;
    // case 0: identity
  }

  return { x: posX + rx, y: posY + ry };
}

// ---------------------------------------------------------------------------
// All analog component type names in the registry
// ---------------------------------------------------------------------------

export const ALL_ANALOG_TYPES: readonly string[] = [
  // Passives
  "Resistor",
  "Capacitor",
  "Inductor",
  "Fuse",
  "Potentiometer",
  "Transformer",
  "TappedTransformer",
  "Crystal",
  "Memristor",
  "PolarizedCap",
  "TransmissionLine",
  // Semiconductors
  "Diode",
  "ZenerDiode",
  "NpnBJT",
  "PnpBJT",
  "NMOS",
  "PMOS",
  "NJFET",
  "PJFET",
  "SCR",
  "Triac",
  "Diac",
  "TunnelDiode",
  "VaractorDiode",
  "Triode",
  // Sources
  "Ground",
  "DcVoltageSource",
  "CurrentSource",
  "AcVoltageSource",
  "VariableRail",
  // Active
  "OpAmp",
  "RealOpAmp",
  "VoltageComparator",
  "Timer555",
  "OTA",
  "Optocoupler",
  "DAC",
  "ADC",
  "VCVS",
  "VCCS",
  "CCVS",
  "CCCS",
  "SchmittInverting",
  "SchmittNonInverting",
  "AnalogSwitchSPST",
  "AnalogSwitchSPDT",
  // Sensors
  "LDR",
  "NTCThermistor",
  "SparkGap",
];
