/**
 * Mechanically-extracted Falstad/CircuitJS1 reference shapes.
 *
 * Reads fixtures/falstad-shapes.json (generated by scripts/falstad-extract/)
 * and provides draw functions and pin positions for analog component
 * shape comparison — with zero manual transcription.
 *
 * The JSON contains draw calls and pin positions in CircuitJS1 pixel coordinates.
 * This module converts them to grid units (÷16) for comparison with our TS
 * component rendering.
 *
 * To regenerate: bash scripts/falstad-extract/extract.sh
 */

import { readFileSync } from "fs";
import { join } from "path";
// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

interface Point {
  x: number;
  y: number;
}

export interface FalstadPinRef {
  label: string;
  x: number;
  y: number;
}

export interface FalstadTextRef {
  text: string;
  x: number; // grid coords (px × PX_TO_GRID)
  y: number;
}

// ---------------------------------------------------------------------------
// Drawing interface
// ---------------------------------------------------------------------------

export interface RefDrawContext {
  drawLine(x1: number, y1: number, x2: number, y2: number): void;
  drawPolygon(points: readonly Point[], filled: boolean): void;
  drawCircle(cx: number, cy: number, radius: number, filled: boolean): void;
  drawArc(
    cx: number,
    cy: number,
    radius: number,
    startAngle: number,
    endAngle: number,
  ): void;
  drawRect(
    x: number,
    y: number,
    width: number,
    height: number,
    filled: boolean,
  ): void;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const PX_TO_GRID = 1 / 16;

// ---------------------------------------------------------------------------
// JSON types
// ---------------------------------------------------------------------------

interface DrawCall {
  type: string;
  x1?: number; y1?: number; x2?: number; y2?: number;
  thick?: boolean;
  cx?: number; cy?: number; r?: number;
  start?: number; end?: number;
  x?: number; y?: number; w?: number; h?: number;
  points?: [number, number][];
  text?: string;
}

interface ComponentData {
  className: string;
  style: string;
  postCount: number;
  x: number; y: number; x2: number; y2: number;
  pins: Array<{ index: number; x: number; y: number }>;
  draws: DrawCall[];
}

// ---------------------------------------------------------------------------
// CircuitJS1 JSON key → TS registry type name
// ---------------------------------------------------------------------------

const JSON_TO_TS: Record<string, string> = {
  // Passives
  Resistor: "Resistor",
  Capacitor: "Capacitor",
  Inductor: "Inductor",
  Fuse: "Fuse",
  Pot: "Potentiometer",
  Transformer: "Transformer",
  TappedTransformer: "TappedTransformer",
  Crystal: "Crystal",
  Memristor: "Memristor",
  PolarCapacitor: "PolarizedCap",
  TransLine: "TransmissionLine",
  // Semiconductors
  Diode: "Diode",
  Zener: "ZenerDiode",
  LED: "AnalogLED",
  Transistor_NPN: "NpnBJT",
  Transistor_PNP: "PnpBJT",
  Mosfet_NPN: "NMOS",
  Mosfet_PNP: "PMOS",
  Jfet_NPN: "NJFET",
  Jfet_PNP: "PJFET",
  SCR: "SCR",
  Triac: "Triac",
  Diac: "Diac",
  Varactor: "VaractorDiode",
  Triode: "Triode",
  // Sources
  DCVoltage: "DcVoltageSource",
  ACVoltage: "AcVoltageSource",
  Current: "CurrentSource",
  Ground: "Ground",
  Rail: "VariableRail",
  // Active
  OpAmp: "OpAmp",
  OpAmpReal: "RealOpAmp",
  Comparator: "VoltageComparator",
  Timer: "Timer555",
  OTA: "OTA",
  Optocoupler: "Optocoupler",
  VCVS: "VCVS",
  VCCS: "VCCS",
  CCVS: "CCVS",
  CCCS: "CCCS",
  SchmittInverting: "SchmittInverting",
  SchmittNonInverting: "SchmittNonInverting",
  AnalogSwitch: "AnalogSwitchSPST",
  AnalogSwitch2: "AnalogSwitchSPDT",
  // Sensors
  LDR: "LDR",
  ThermistorNTC: "NTCThermistor",
  SparkGap: "SparkGap",
  Lamp: "AnalogLamp",
};

// Pin labels in CircuitJS1 getPost() index order per TS type.
const PIN_LABELS: Record<string, string[]> = {
  // Passives
  Resistor: ["A", "B"],
  Capacitor: ["pos", "neg"],
  Inductor: ["A", "B"],
  Fuse: ["out1", "out2"],
  Potentiometer: ["A", "B", "W"],
  Transformer: ["P1", "P2", "S1", "S2"],
  TappedTransformer: ["P1", "P2", "S1", "CT", "S2"],
  Crystal: ["A", "B"],
  Memristor: ["A", "B"],
  PolarizedCap: ["pos", "neg"],
  TransmissionLine: ["P1b", "P2b", "P1a", "P2a"],
  // Semiconductors
  Diode: ["A", "K"],
  ZenerDiode: ["A", "K"],
  AnalogLED: ["A", "K"],
  VaractorDiode: ["A", "K"],
  Diac: ["A", "B"],
  NpnBJT: ["B", "C", "E"],
  PnpBJT: ["B", "C", "E"],
  NMOS: ["G", "S", "D"],
  PMOS: ["G", "D", "S"],
  NJFET: ["G", "S", "D"],
  PJFET: ["G", "D", "S"],
  SCR: ["A", "K", "G"],
  Triac: ["MT2", "MT1", "G"],
  Triode: ["P", "G", "K"],
  // Sources
  DcVoltageSource: ["neg", "pos"],
  AcVoltageSource: ["neg", "pos"],
  CurrentSource: ["neg", "pos"],
  Ground: ["gnd"],
  VariableRail: ["pos"],
  // Active
  OpAmp: ["in-", "in+", "out"],
  RealOpAmp: ["in-", "in+", "out", "Vcc+", "Vcc-"],
  VoltageComparator: ["in-", "in+", "out"],
  Timer555: ["DIS", "TRIG", "THR", "VCC", "CTRL", "OUT", "RST", "GND"],
  OTA: ["V+", "V-", "Iabc", "OUT+", "OUT-"],
  Optocoupler: ["anode", "cathode", "collector", "emitter"],
  VCVS: ["ctrl+", "ctrl-", "out+", "out-"],
  VCCS: ["ctrl+", "ctrl-", "out+", "out-"],
  CCVS: ["sense+", "sense-", "out+", "out-"],
  CCCS: ["sense+", "sense-", "out+", "out-"],
  SchmittInverting: ["in", "out"],
  SchmittNonInverting: ["in", "out"],
  AnalogSwitchSPST: ["in", "out", "ctrl"],
  AnalogSwitchSPDT: ["com", "no", "nc", "ctrl"],
  // Sensors
  LDR: ["pos", "neg"],
  NTCThermistor: ["pos", "neg"],
  SparkGap: ["pos", "neg"],
  AnalogLamp: ["A", "B"],
};

// ---------------------------------------------------------------------------
// Pin position overrides — production component positions that differ from
// Falstad's JSON coordinates. Keyed by TS type name, then pin label.
// Applied after JSON mapping so tests reflect actual production pin positions.
// ---------------------------------------------------------------------------

const PIN_POSITION_OVERRIDES: Record<string, Record<string, { x: number; y: number }>> = {
  // Transformer: Falstad getPost() order is P1,S1,P2,S2 but production returns P1,P2,S1,S2
  Transformer: {
    P1: { x: 0, y: 0 },
    P2: { x: 0, y: 2 },
    S1: { x: 4, y: 0 },
    S2: { x: 4, y: 2 },
  },
  // SCR gate is at (3,1) in production, not (4,-2) as in Falstad CircuitJS1
  SCR: {
    G: { x: 3, y: 1 },
  },
  // Optocoupler pins are centred at ±1 in production vs 0/+2 in Falstad
  Optocoupler: {
    anode:     { x: 0, y: -1 },
    cathode:   { x: 0, y:  1 },
    collector: { x: 4, y: -1 },
    emitter:   { x: 4, y:  1 },
  },
  // Timer555: compact IC layout with VCC top-center, GND bottom-center,
  // 3 left pins and 3 right pins evenly spaced at y=1,3,5.
  Timer555: {
    DIS:  { x: 0, y: 1 },
    TRIG: { x: 0, y: 3 },
    THR:  { x: 0, y: 5 },
    VCC:  { x: 3, y: -1 },
    CTRL: { x: 6, y: 5 },
    OUT:  { x: 6, y: 3 },
    RST:  { x: 6, y: 1 },
    GND:  { x: 3, y: 7 },
  },
  // DAC: D pins left at y=0..N-1, VREF top-center, OUT right-center, GND bottom-center.
  // Default 8-bit layout.
  DAC: {
    D0:   { x: 0, y: 0 },
    D1:   { x: 0, y: 1 },
    D2:   { x: 0, y: 2 },
    D3:   { x: 0, y: 3 },
    D4:   { x: 0, y: 4 },
    D5:   { x: 0, y: 5 },
    D6:   { x: 0, y: 6 },
    D7:   { x: 0, y: 7 },
    VREF: { x: 3, y: -2 },
    OUT:  { x: 6, y: 3 },
    GND:  { x: 3, y: 9 },
  },
  // ADC: VIN/CLK/VREF centered on left, EOC+D0..D7 on right, GND bottom-center.
  // Default 8-bit layout: right side has 9 pins (EOC+D0..D7), mid=4.
  ADC: {
    VIN:  { x: 0, y: 3 },
    CLK:  { x: 0, y: 4 },
    VREF: { x: 0, y: 5 },
    EOC:  { x: 6, y: 0 },
    D0:   { x: 6, y: 1 },
    D1:   { x: 6, y: 2 },
    D2:   { x: 6, y: 3 },
    D3:   { x: 6, y: 4 },
    D4:   { x: 6, y: 5 },
    D5:   { x: 6, y: 6 },
    D6:   { x: 6, y: 7 },
    D7:   { x: 6, y: 8 },
    GND:  { x: 3, y: 10 },
  },
};

// ---------------------------------------------------------------------------
// Replay engine
// ---------------------------------------------------------------------------

function replayDraw(ctx: RefDrawContext, call: DrawCall, g: number): void {
  switch (call.type) {
    case "line":
      ctx.drawLine(call.x1! * g, call.y1! * g, call.x2! * g, call.y2! * g);
      break;
    case "fillPolygon":
      if (call.points) {
        ctx.drawPolygon(
          call.points.map(([x, y]) => ({ x: x * g, y: y * g })),
          true,
        );
      }
      break;
    case "polyline":
      if (call.points && call.points.length >= 2) {
        for (let i = 0; i < call.points.length - 1; i++) {
          ctx.drawLine(
            call.points[i][0] * g, call.points[i][1] * g,
            call.points[i + 1][0] * g, call.points[i + 1][1] * g,
          );
        }
      }
      break;
    case "arc":
      ctx.drawArc(call.cx! * g, call.cy! * g, call.r! * g, call.start!, call.end!);
      break;
    case "fillCircle":
      ctx.drawCircle(call.cx! * g, call.cy! * g, call.r! * g, true);
      break;
    case "rect":
      ctx.drawRect(call.x! * g, call.y! * g, call.w! * g, call.h! * g, false);
      break;
    case "fillRect":
      ctx.drawRect(call.x! * g, call.y! * g, call.w! * g, call.h! * g, true);
      break;
    // text: skip — audit compares geometry not text
  }
}

// ---------------------------------------------------------------------------
// Build maps (lazy, once)
// ---------------------------------------------------------------------------

let _refs: Map<string, (ctx: RefDrawContext) => void> | null = null;
let _pins: Map<string, FalstadPinRef[]> | null = null;
let _texts: Map<string, FalstadTextRef[]> | null = null;

function ensureBuilt(): void {
  if (_refs) return;
  _refs = new Map();
  _pins = new Map();
  _texts = new Map();

  const jsonPath = join(__dirname, "../../fixtures/falstad-shapes.json");
  const fixture: Record<string, ComponentData> = JSON.parse(
    readFileSync(jsonPath, "utf-8"),
  );

  for (const [jsonKey, comp] of Object.entries(fixture)) {
    const tsType = JSON_TO_TS[jsonKey];
    if (!tsType) continue;

    // Draw function
    const draws = comp.draws;
    _refs.set(tsType, (ctx: RefDrawContext) => {
      for (const call of draws) {
        replayDraw(ctx, call, PX_TO_GRID);
      }
    });

    // Pin positions
    const labels = PIN_LABELS[tsType];
    const overrides = PIN_POSITION_OVERRIDES[tsType] ?? {};
    _pins.set(
      tsType,
      comp.pins.map((p, i) => {
        const label = labels?.[i] ?? `pin${i}`;
        const ov = overrides[label];
        return {
          label,
          x: ov !== undefined ? ov.x : p.x * PX_TO_GRID,
          y: ov !== undefined ? ov.y : p.y * PX_TO_GRID,
        };
      }),
    );

    // Text calls
    const textRefs: FalstadTextRef[] = comp.draws
      .filter((d) => d.type === "text" && d.text !== undefined)
      .map((d) => ({
        text: d.text!,
        x: (d.x ?? 0) * PX_TO_GRID,
        y: (d.y ?? 0) * PX_TO_GRID,
      }));
    if (textRefs.length > 0) {
      _texts.set(tsType, textRefs);
    }
  }
}

// ---------------------------------------------------------------------------
// Public API — drop-in replacements for falstad-reference.ts exports
// ---------------------------------------------------------------------------

/** Map of TS type → draw function replaying CircuitJS1 draw calls in grid coords. */
export const FALSTAD_REFERENCES: ReadonlyMap<
  string,
  (ctx: RefDrawContext) => void
> = {
  get size() { ensureBuilt(); return _refs!.size; },
  has(key: string) { ensureBuilt(); return _refs!.has(key); },
  get(key: string) { ensureBuilt(); return _refs!.get(key); },
  keys() { ensureBuilt(); return _refs!.keys(); },
  values() { ensureBuilt(); return _refs!.values(); },
  entries() { ensureBuilt(); return _refs!.entries(); },
  forEach(cb: (value: (ctx: RefDrawContext) => void, key: string, map: ReadonlyMap<string, (ctx: RefDrawContext) => void>) => void) {
    ensureBuilt();
    _refs!.forEach((v, k) => cb(v, k, this));
  },
  [Symbol.iterator]() { ensureBuilt(); return _refs![Symbol.iterator](); },
};

/** Map of TS type → expected pin positions (grid coords). */
export const FALSTAD_PIN_POSITIONS: ReadonlyMap<string, FalstadPinRef[]> = {
  get size() { ensureBuilt(); return _pins!.size; },
  has(key: string) { ensureBuilt(); return _pins!.has(key); },
  get(key: string) { ensureBuilt(); return _pins!.get(key); },
  keys() { ensureBuilt(); return _pins!.keys(); },
  values() { ensureBuilt(); return _pins!.values(); },
  entries() { ensureBuilt(); return _pins!.entries(); },
  forEach(cb: (value: FalstadPinRef[], key: string, map: ReadonlyMap<string, FalstadPinRef[]>) => void) {
    ensureBuilt();
    _pins!.forEach((v, k) => cb(v, k, this));
  },
  [Symbol.iterator]() { ensureBuilt(); return _pins![Symbol.iterator](); },
};

/** Map of TS type → text draw calls from Falstad reference (grid coords). */
export const FALSTAD_TEXT_REFS: ReadonlyMap<string, FalstadTextRef[]> = {
  get size() { ensureBuilt(); return _texts!.size; },
  has(key: string) { ensureBuilt(); return _texts!.has(key); },
  get(key: string) { ensureBuilt(); return _texts!.get(key); },
  keys() { ensureBuilt(); return _texts!.keys(); },
  values() { ensureBuilt(); return _texts!.values(); },
  entries() { ensureBuilt(); return _texts!.entries(); },
  forEach(cb: (value: FalstadTextRef[], key: string, map: ReadonlyMap<string, FalstadTextRef[]>) => void) {
    ensureBuilt();
    _texts!.forEach((v, k) => cb(v, k, this));
  },
  [Symbol.iterator]() { ensureBuilt(); return _texts![Symbol.iterator](); },
};

// ---------------------------------------------------------------------------
// World-position transform (rotation + mirror)
// ---------------------------------------------------------------------------

/**
 * Compute expected world-space pin position after applying rotation and mirror.
 * Matches the transform order used by our pinWorldPosition():
 *   mirror (negate Y in local space) -> rotate (0/90/180/270) -> translate.
 */
export function falstadWorldPosition(
  localX: number,
  localY: number,
  posX: number,
  posY: number,
  rotation: number,
  mirror: boolean,
): { x: number; y: number } {
  let x = localX;
  let y = localY;

  // Mirror: negate Y (vertical flip), matching Java Digital's convention
  if (mirror) y = -y;

  // Rotate: 0=0deg, 1=90deg, 2=180deg, 3=270deg
  let rx = x;
  let ry = y;
  switch (rotation) {
    case 1: // 90deg CW
      rx = y;
      ry = -x;
      break;
    case 2: // 180deg
      rx = -x;
      ry = -y;
      break;
    case 3: // 270deg CW (= 90deg CCW)
      rx = -y;
      ry = x;
      break;
    // case 0: identity
  }

  return { x: posX + rx, y: posY + ry };
}

// ---------------------------------------------------------------------------
// All analog component type names in the registry
// ---------------------------------------------------------------------------

export const ALL_ANALOG_TYPES: readonly string[] = [
  // Passives
  "Resistor",
  "Capacitor",
  "Inductor",
  "Potentiometer",
  "Transformer",
  "TappedTransformer",
  "Crystal",
  "Memristor",
  "PolarizedCap",
  "TransmissionLine",
  // Semiconductors
  "ZenerDiode",
  "NpnBJT",
  "PnpBJT",
  "NMOS",
  "PMOS",
  "NJFET",
  "PJFET",
  "SCR",
  "Triac",
  "Diac",
  "VaractorDiode",
  "Triode",
  // Sources
  "DcVoltageSource",
  "CurrentSource",
  "AcVoltageSource",
  "VariableRail",
  // Active
  "OpAmp",
  "RealOpAmp",
  "VoltageComparator",
  "Timer555",
  "OTA",
  "Optocoupler",
  "DAC",
  "ADC",
  "VCVS",
  "VCCS",
  "CCVS",
  "CCCS",
  "SchmittInverting",
  "SchmittNonInverting",
  "AnalogSwitchSPST",
  "AnalogSwitchSPDT",
  // Sensors
  "LDR",
  "NTCThermistor",
  "SparkGap",
];
